import { useEffect } from "react";
import { useLanguage } from "./LanguageContext";

/*
 * Centralized language bridge for the existing FraudShield pages.
 *
 * Why this exists:
 * The project has many existing pages with their own JSX/CSS and we do not
 * want to rewrite business logic just to introduce i18n. This bridge
 * translates the static UI text rendered by those pages while leaving
 * dynamic values (names, email addresses, IDs, amounts, API responses, etc.)
 * alone.
 */

const PHRASES = {
  hi: {
    "FraudShield AI": "फ्रॉडशील्ड AI",
    "REAL-TIME FRAUD INTELLIGENCE": "रियल-टाइम फ्रॉड इंटेलिजेंस",
    "Real-Time Transaction Protection": "रियल-टाइम लेनदेन सुरक्षा",
    "SECURE FRAUD INTELLIGENCE": "सुरक्षित फ्रॉड इंटेलिजेंस",
    "FRAUDSHIELD SECURITY OPERATIONS CENTER": "फ्रॉडशील्ड सुरक्षा संचालन केंद्र",
    "Fraud Intelligence Command Center": "फ्रॉड इंटेलिजेंस कमांड सेंटर",
    "Fraud Alert Center": "फ्रॉड अलर्ट केंद्र",
    "FRAUD ALERT CENTER": "फ्रॉड अलर्ट केंद्र",
    "Fraud Intelligence Network": "फ्रॉड इंटेलिजेंस नेटवर्क",
    "Fraud Network": "फ्रॉड नेटवर्क",
    "Fraud Analytics": "फ्रॉड एनालिटिक्स",
    "Geographic Fraud": "भौगोलिक फ्रॉड",
    "Geographic Intelligence": "भौगोलिक इंटेलिजेंस",
    "Device Intelligence": "डिवाइस इंटेलिजेंस",
    "DEVICE & BENEFICIARY INTELLIGENCE": "डिवाइस और लाभार्थी इंटेलिजेंस",
    "BENEFICIARY INTELLIGENCE": "लाभार्थी इंटेलिजेंस",
    "User Risk Profile": "उपयोगकर्ता जोखिम प्रोफ़ाइल",
    "USER RISK INTELLIGENCE": "उपयोगकर्ता जोखिम इंटेलिजेंस",
    "Voice Phishing Protection": "वॉइस फ़िशिंग सुरक्षा",
    "Voice Phishing": "वॉइस फ़िशिंग",
    "Voice Phishing AI": "वॉइस फ़िशिंग AI",
    "Voice Analyzer": "वॉइस विश्लेषक",
    "Features": "विशेषताएँ",
    "Security": "सुरक्षा",
    "How It Works": "यह कैसे काम करता है",
    "Back to Dashboard": "डैशबोर्ड पर वापस जाएँ",
    "Back to Login": "लॉगिन पर वापस जाएँ",
    "Back to home": "होम पर वापस जाएँ",
    "Get Started": "शुरू करें",
    "Login": "लॉगिन",
    "Logout": "लॉगआउट",
    "Register": "रजिस्टर",
    "Dashboard": "डैशबोर्ड",
    "Transaction": "लेनदेन",
    "Transactions": "लेनदेन",
    "Alerts": "अलर्ट",
    "Analytics": "एनालिटिक्स",
    "Network": "नेटवर्क",
    "Geography": "भूगोल",
    "Devices": "डिवाइस",
    "Beneficiaries": "लाभार्थी",
    "Locations": "स्थान",
    "Admin": "एडमिन",
    "Settings": "सेटिंग्स",
    "Real-Time Detection": "रियल-टाइम पहचान",
    "Real-Time Monitoring": "रियल-टाइम मॉनिटरिंग",
    "Real-Time Transaction Protection": "रियल-टाइम लेनदेन सुरक्षा",
    "Explainable AI": "समझाने योग्य AI",
    "Explainable Risk Signals": "समझाने योग्य जोखिम संकेत",
    "Explainable AI Decisions": "समझाने योग्य AI निर्णय",
    "Privacy First": "गोपनीयता पहले",
    "Powerful Protection": "शक्तिशाली सुरक्षा",
    "POWERFUL PROTECTION": "शक्तिशाली सुरक्षा",
    "Stop Fraud": "धोखाधड़ी रोकें",
    "Before It Happens.": "होने से पहले।",
    "Protect My Account": "मेरे खाते को सुरक्षित करें",
    "See How It Works": "देखें यह कैसे काम करता है",
    "AI-Powered Real-Time Protection": "AI-संचालित रियल-टाइम सुरक्षा",
    "Suspicious Activity": "संदिग्ध गतिविधि",
    "Suspicious activity": "संदिग्ध गतिविधि",
    "Multiple unusual signals detected": "कई असामान्य संकेत मिले",
    "New beneficiary": "नया लाभार्थी",
    "New device": "नया डिवाइस",
    "Unusual amount": "असामान्य राशि",
    "Suspicious voice interaction": "संदिग्ध वॉइस इंटरैक्शन",
    "Review Transaction": "लेनदेन की समीक्षा करें",
    "Review Status": "समीक्षा स्थिति",
    "Review": "समीक्षा",
    "Reviewed": "समीक्षित",
    "Already Reviewed": "पहले ही समीक्षा की गई",
    "Mark as Reviewed": "समीक्षित के रूप में चिह्नित करें",
    "Mark as read": "पढ़ा हुआ चिह्नित करें",
    "Mark Read": "पढ़ा हुआ चिह्नित करें",
    "High Risk": "उच्च जोखिम",
    "HIGH RISK": "उच्च जोखिम",
    "High Risk Alerts": "उच्च जोखिम वाले अलर्ट",
    "Medium Risk": "मध्यम जोखिम",
    "MEDIUM RISK": "मध्यम जोखिम",
    "Low Risk": "कम जोखिम",
    "LOW RISK": "कम जोखिम",
    "High": "उच्च",
    "Medium": "मध्यम",
    "Low": "कम",
    "Blocked": "ब्लॉक किए गए",
    "Blocked Transactions": "ब्लॉक किए गए लेनदेन",
    "Allowed": "अनुमत",
    "Needs Review": "समीक्षा आवश्यक",
    "Pending": "लंबित",
    "Confirmed": "पुष्ट",
    "Confirmed Fraud": "पुष्ट धोखाधड़ी",
    "False Positive": "गलत सकारात्मक",
    "Human Review": "मानवीय समीक्षा",
    "Unread": "अपठित",
    "No active alerts": "कोई सक्रिय अलर्ट नहीं",
    "No Fraud Alerts": "कोई फ्रॉड अलर्ट नहीं",
    "No fraud alerts": "कोई फ्रॉड अलर्ट नहीं",
    "No matching alerts": "कोई मेल खाते अलर्ट नहीं",
    "No matching entities": "कोई मेल खाती एंटिटी नहीं",
    "No matching locations": "कोई मेल खाते स्थान नहीं",
    "No network data yet": "अभी कोई नेटवर्क डेटा नहीं है",
    "No relationships were found for this entity.": "इस एंटिटी के लिए कोई संबंध नहीं मिला।",
    "No risk signals available.": "कोई जोखिम संकेत उपलब्ध नहीं हैं।",
    "No risk signals detected": "कोई जोखिम संकेत नहीं मिले",
    "No transactions available.": "कोई लेनदेन उपलब्ध नहीं है।",
    "No transactions found": "कोई लेनदेन नहीं मिला",
    "No devices found": "कोई डिवाइस नहीं मिला",
    "No beneficiaries found": "कोई लाभार्थी नहीं मिला",
    "No location data found": "स्थान का कोई डेटा नहीं मिला",
    "No high-risk locations": "कोई उच्च जोखिम वाला स्थान नहीं है",
    "Risk Assessment": "जोखिम आकलन",
    "Overall Risk Score": "कुल जोखिम स्कोर",
    "RISK SCORE": "जोखिम स्कोर",
    "RISK LEVEL": "जोखिम स्तर",
    "OVERALL RISK": "कुल जोखिम",
    "Transaction Risk": "लेनदेन जोखिम",
    "Transaction Risk Analyzer": "लेनदेन जोखिम विश्लेषक",
    "Transaction Actions": "लेनदेन कार्रवाइयाँ",
    "Transaction Context": "लेनदेन संदर्भ",
    "Transaction Amount": "लेनदेन राशि",
    "Transaction History": "लेनदेन इतिहास",
    "Recent Transactions": "हाल के लेनदेन",
    "Recent Fraud Alerts": "हाल के फ्रॉड अलर्ट",
    "Top Risk Signals": "शीर्ष जोखिम संकेत",
    "Fraud Indicators": "फ्रॉड संकेतक",
    "Detected Signals": "पहचाने गए संकेत",
    "DETECTED SIGNALS": "पहचाने गए संकेत",
    "DETECTED PHISHING INDICATORS": "पहचाने गए फ़िशिंग संकेतक",
    "Why this score?": "यह स्कोर क्यों?",
    "WHY THIS DECISION?": "यह निर्णय क्यों?",
    "Recommended Action": "अनुशंसित कार्रवाई",
    "RECOMMENDED ACTION": "अनुशंसित कार्रवाई",
    "Protect": "सुरक्षित करें",
    "Analyze": "विश्लेषण करें",
    "Analyze Transaction": "लेनदेन का विश्लेषण करें",
    "Analyzing...": "विश्लेषण हो रहा है...",
    "Analyzing Conversation...": "बातचीत का विश्लेषण हो रहा है...",
    "Retry": "पुनः प्रयास",
    "Try Again": "फिर से प्रयास करें",
    "Refresh": "रिफ्रेश",
    "Refresh Intelligence": "इंटेलिजेंस रिफ्रेश करें",
    "Refresh Alerts": "अलर्ट रिफ्रेश करें",
    "Refresh Network": "नेटवर्क रिफ्रेश करें",
    "Refreshing...": "रिफ्रेश हो रहा है...",
    "Reset Analysis": "विश्लेषण रीसेट करें",
    "Search": "खोजें",
    "Search Network Entities": "नेटवर्क एंटिटी खोजें",
    "Search Geographic Entities": "भौगोलिक एंटिटी खोजें",
    "Clear": "साफ़ करें",
    "Close": "बंद करें",
    "Dismiss": "हटाएँ",
    "Investigate": "जांच करें",
    "INVESTIGATE": "जांच करें",
    "Investigation Tools": "जांच उपकरण",
    "INVESTIGATION TOOLS": "जांच उपकरण",
    "Investigation Workflow": "जांच कार्यप्रवाह",
    "Continue Investigation": "जांच जारी रखें",
    "Open Alerts": "अलर्ट खोलें",
    "Open Fraud Alerts": "फ्रॉड अलर्ट खोलें",
    "Open Fraud Network": "फ्रॉड नेटवर्क खोलें",
    "Open Geography": "भूगोल खोलें",
    "Open Transaction Analyzer": "लेनदेन विश्लेषक खोलें",
    "Open Voice Detector": "वॉइस डिटेक्टर खोलें",
    "Open Analyst Center": "विश्लेषक केंद्र खोलें",
    "View Alerts": "अलर्ट देखें",
    "View Analytics": "एनालिटिक्स देखें",
    "View Risk Profile": "जोखिम प्रोफ़ाइल देखें",
    "View Security Center": "सुरक्षा केंद्र देखें",
    "Live Call Detection": "लाइव कॉल पहचान",
    "LIVE TRANSCRIPT": "लाइव ट्रांसक्रिप्ट",
    "CALL TRANSCRIPT": "कॉल ट्रांसक्रिप्ट",
    "Conversation Analysis": "बातचीत विश्लेषण",
    "AI Assessment": "AI आकलन",
    "Upload call recording": "कॉल रिकॉर्डिंग अपलोड करें",
    "OR PASTE TRANSCRIPT": "या ट्रांसक्रिप्ट पेस्ट करें",
    "Automatic AI analysis": "स्वचालित AI विश्लेषण",
    "Start Live Detection": "लाइव पहचान शुरू करें",
    "Stop Detection": "पहचान रोकें",
    "Awaiting conversation": "बातचीत की प्रतीक्षा",
    "Waiting for speech": "स्पीच की प्रतीक्षा",
    "Voice Scam Detection": "वॉइस स्कैम पहचान",
    "Analyze for Phishing": "फ़िशिंग के लिए विश्लेषण करें",
    "AI ENGINE ONLINE": "AI इंजन ऑनलाइन",
    "AI ENGINE READY": "AI इंजन तैयार",
    "Microphone active": "माइक्रोफ़ोन सक्रिय",
    "Microphone permission was denied. Allow microphone access and try again.": "माइक्रोफ़ोन अनुमति अस्वीकार की गई। माइक्रोफ़ोन की अनुमति दें और फिर प्रयास करें।",
    "REAL-TIME FRAUD ENGINE": "रियल-टाइम फ्रॉड इंजन",
    "AI CONFIDENCE": "AI विश्वास स्तर",
    "AI DECISION": "AI निर्णय",
    "AI DECISIONS": "AI निर्णय",
    "AI EXPLAINABILITY": "AI व्याख्येयता",
    "AI Explanation": "AI व्याख्या",
    "AI RISK LEVEL": "AI जोखिम स्तर",
    "Rule evaluation": "नियम मूल्यांकन",
    "ML risk scoring": "ML जोखिम स्कोरिंग",
    "Machine Learning": "मशीन लर्निंग",
    "Signals Used by the Engine": "इंजन द्वारा उपयोग किए गए संकेत",
    "Behavior Intelligence": "व्यवहार इंटेलिजेंस",
    "Behaviour Intelligence": "व्यवहार इंटेलिजेंस",
    "BEHAVIORAL SECURITY SIGNALS": "व्यवहारिक सुरक्षा संकेत",
    "BEHAVIORAL RISK": "व्यवहारिक जोखिम",
    "FRAUD INTELLIGENCE": "फ्रॉड इंटेलिजेंस",
    "FRAUD INVESTIGATION": "फ्रॉड जांच",
    "ENTERPRISE FRAUD INTELLIGENCE": "एंटरप्राइज़ फ्रॉड इंटेलिजेंस",
    "SECURITY OPERATIONS": "सुरक्षा संचालन",
    "SECURITY MONITORING": "सुरक्षा मॉनिटरिंग",
    "SECURITY OVERVIEW": "सुरक्षा अवलोकन",
    "LIVE SECURITY ALERTS": "लाइव सुरक्षा अलर्ट",
    "LIVE FRAUD EVENT": "लाइव फ्रॉड घटना",
    "LIVE TELEMETRY": "लाइव टेलीमेट्री",
    "LIVE MONITORING": "लाइव मॉनिटरिंग",
    "LIVE NETWORK": "लाइव नेटवर्क",
    "ALL SYSTEMS OPERATIONAL": "सभी सिस्टम चालू हैं",
    "Protection active": "सुरक्षा सक्रिय",
    "Loaded from backend": "बैकएंड से लोड किया गया",
    "Loading fraud alerts": "फ्रॉड अलर्ट लोड हो रहे हैं",
    "Loading fraud alerts...": "फ्रॉड अलर्ट लोड हो रहे हैं...",
    "Loading Fraud Intelligence": "फ्रॉड इंटेलिजेंस लोड हो रही है",
    "Loading fraud intelligence...": "फ्रॉड इंटेलिजेंस लोड हो रही है...",
    "Loading intelligence...": "इंटेलिजेंस लोड हो रही है...",
    "Loading geographic intelligence": "भौगोलिक इंटेलिजेंस लोड हो रही है",
    "Loading users, transactions, devices, beneficiaries and locations.": "यूज़र, लेनदेन, डिवाइस, लाभार्थी और स्थान लोड हो रहे हैं।",
    "Connecting to fraud detection engine...": "फ्रॉड डिटेक्शन इंजन से कनेक्ट हो रहा है...",
    "Connecting to the FraudShield backend.": "FraudShield बैकएंड से कनेक्ट हो रहा है।",
    "Intelligence engine unavailable": "इंटेलिजेंस इंजन उपलब्ध नहीं है",
    "Intelligence service error": "इंटेलिजेंस सेवा त्रुटि",
    "Unable to load alerts": "अलर्ट लोड नहीं हो सके",
    "Unable to load analytics": "एनालिटिक्स लोड नहीं हो सके",
    "Unable to load fraud alerts.": "फ्रॉड अलर्ट लोड नहीं हो सके।",
    "Unable to load fraud analytics.": "फ्रॉड एनालिटिक्स लोड नहीं हो सके।",
    "Unable to load device and beneficiary intelligence.": "डिवाइस और लाभार्थी इंटेलिजेंस लोड नहीं हो सकी।",
    "Unable to load geographic fraud intelligence.": "भौगोलिक फ्रॉड इंटेलिजेंस लोड नहीं हो सकी।",
    "Unable to load user risk profile.": "उपयोगकर्ता जोखिम प्रोफ़ाइल लोड नहीं हो सकी।",
    "Admin Controls": "एडमिन नियंत्रण",
    "Alert Management": "अलर्ट प्रबंधन",
    "Analyst Center": "विश्लेषक केंद्र",
    "Analyst Review": "विश्लेषक समीक्षा",
    "Analyst Feedback": "विश्लेषक प्रतिक्रिया",
    "Total Alerts": "कुल अलर्ट",
    "TOTAL ALERTS": "कुल अलर्ट",
    "UNREAD ALERTS": "अपठित अलर्ट",
    "AMOUNT AT RISK": "जोखिम में राशि",
    "AVERAGE RISK": "औसत जोखिम",
    "TOTAL TRANSACTIONS": "कुल लेनदेन",
    "Total Transactions": "कुल लेनदेन",
    "Total Devices": "कुल डिवाइस",
    "Known Devices": "ज्ञात डिवाइस",
    "Known Beneficiaries": "ज्ञात लाभार्थी",
    "Connections": "कनेक्शन",
    "Network relationships": "नेटवर्क संबंध",
    "NETWORK CONNECTIONS": "नेटवर्क कनेक्शन",
    "NETWORK CONTEXT": "नेटवर्क संदर्भ",
    "NETWORK EDGES": "नेटवर्क एज",
    "NETWORK RISK": "नेटवर्क जोखिम",
    "Network Risk": "नेटवर्क जोखिम",
    "All Risk Levels": "सभी जोखिम स्तर",
    "All Types": "सभी प्रकार",
    "All": "सभी",
    "High risk transactions": "उच्च जोखिम वाले लेनदेन",
    "High-risk transactions": "उच्च जोखिम वाले लेनदेन",
    "High-risk locations should be investigated alongside transaction and device signals.": "उच्च जोखिम वाले स्थानों की जांच लेनदेन और डिवाइस संकेतों के साथ की जानी चाहिए।",
    "Risk calculated from recent transactions and connected fraud entities.": "जोखिम की गणना हाल के लेनदेन और जुड़े फ्रॉड एंटिटी से की गई है।",
    "Review the transaction risk signals associated with this user.": "इस उपयोगकर्ता से जुड़े लेनदेन जोखिम संकेतों की समीक्षा करें।",
    "Consolidated behavioral intelligence across transactions, devices, beneficiaries, locations and fraud alerts.": "लेनदेन, डिवाइस, लाभार्थी, स्थान और फ्रॉड अलर्ट से संयुक्त व्यवहारिक इंटेलिजेंस।",
    "Review suspicious transactions, alerts and AI fraud decisions.": "संदिग्ध लेनदेन, अलर्ट और AI फ्रॉड निर्णयों की समीक्षा करें।",
    "Review individual transaction decisions and risk scores.": "व्यक्तिगत लेनदेन निर्णय और जोखिम स्कोर की समीक्षा करें।",
    "Monitor suspicious transactions and investigate real-time fraud signals.": "संदिग्ध लेनदेन की निगरानी करें और रियल-टाइम फ्रॉड संकेतों की जांच करें।",
    "Monitor suspicious transactions, investigate fraud alerts and review AI decisions.": "संदिग्ध लेनदेन की निगरानी करें, फ्रॉड अलर्ट की जांच करें और AI निर्णयों की समीक्षा करें।",
    "Filter and review suspicious transactions detected by FraudShield AI.": "FraudShield AI द्वारा पहचाने गए संदिग्ध लेनदेन को फ़िल्टर और समीक्षा करें।",
    "Analyze UPI transactions using behavioral signals and AI-powered fraud detection.": "व्यवहारिक संकेतों और AI-संचालित फ्रॉड पहचान का उपयोग करके UPI लेनदेन का विश्लेषण करें।",
    "Analyze transaction locations and suspicious geographic activity.": "लेनदेन स्थानों और संदिग्ध भौगोलिक गतिविधि का विश्लेषण करें।",
    "Analyze transactions with device, beneficiary or location identifiers to build the network.": "नेटवर्क बनाने के लिए डिवाइस, लाभार्थी या स्थान पहचानकर्ताओं वाले लेनदेन का विश्लेषण करें।",
    "Analyze device behavior, suspicious sessions and transaction-device relationships.": "डिवाइस व्यवहार, संदिग्ध सत्र और लेनदेन-डिवाइस संबंधों का विश्लेषण करें।",
    "Find suspicious devices and beneficiaries quickly.": "संदिग्ध डिवाइस और लाभार्थी जल्दी खोजें।",
    "Find suspicious devices, beneficiaries, locations or transactions quickly.": "संदिग्ध डिवाइस, लाभार्थी, स्थान या लेनदेन जल्दी खोजें।",
    "Find suspicious locations and investigate their network relationships.": "संदिग्ध स्थान खोजें और उनके नेटवर्क संबंधों की जांच करें।",
    "See how devices and beneficiaries relate to transactions and locations.": "देखें कि डिवाइस और लाभार्थी लेनदेन और स्थानों से कैसे जुड़े हैं।",
    "Beneficiaries connected to your transaction network.": "आपके लेनदेन नेटवर्क से जुड़े लाभार्थी।",
    "Devices connected to your stored transaction network.": "आपके संग्रहीत लेनदेन नेटवर्क से जुड़े डिवाइस।",
    "Fraud network intelligence is connected to the live backend.": "फ्रॉड नेटवर्क इंटेलिजेंस लाइव बैकएंड से जुड़ी है।",
    "FraudShield is analyzing your fraud-network entities.": "FraudShield आपकी फ्रॉड-नेटवर्क एंटिटी का विश्लेषण कर रहा है।",
    "Known network devices": "ज्ञात नेटवर्क डिवाइस",
    "Connected destinations": "जुड़े हुए गंतव्य",
    "Entities requiring attention": "ध्यान देने वाली एंटिटी",
    "INVESTIGATION WORKFLOW": "जांच कार्यप्रवाह",
    "Continue Investigation": "जांच जारी रखें",
    "Combine geographic evidence with transactions, devices, alerts and network relationships.": "भौगोलिक साक्ष्य को लेनदेन, डिवाइस, अलर्ट और नेटवर्क संबंधों के साथ जोड़ें।",
    "Geographic entities": "भौगोलिक एंटिटी",
    "Geographic entities connected to your fraud intelligence network.": "आपके फ्रॉड इंटेलिजेंस नेटवर्क से जुड़ी भौगोलिक एंटिटी।",
    "Geographic Risk Distribution": "भौगोलिक जोखिम वितरण",
    "Geographic Signals": "भौगोलिक संकेत",
    "LOCATION RISK INTELLIGENCE": "स्थान जोखिम इंटेलिजेंस",
    "LOCATION INVESTIGATION": "स्थान जांच",
    "Locations Requiring Attention": "ध्यान देने वाले स्थान",
    "Observed Locations": "देखे गए स्थान",
    "No high-risk locations": "कोई उच्च जोखिम वाला स्थान नहीं है",
    "Geographic intelligence currently shows no high-risk locations.": "भौगोलिक इंटेलिजेंस में अभी कोई उच्च जोखिम वाला स्थान नहीं दिख रहा है।",
    "Geographic intelligence error:": "भौगोलिक इंटेलिजेंस त्रुटि:",
    "Geographic risk should be reviewed together with transaction amount, device, beneficiary, timing and other fraud signals.": "भौगोलिक जोखिम की समीक्षा लेनदेन राशि, डिवाइस, लाभार्थी, समय और अन्य फ्रॉड संकेतों के साथ की जानी चाहिए।",
    "Create Secure Account": "सुरक्षित खाता बनाएँ",
    "Create a FraudShield account": "FraudShield खाता बनाएँ",
    "Create your account": "अपना खाता बनाएँ",
    "Creating Account...": "खाता बनाया जा रहा है...",
    "Welcome back": "वापसी पर स्वागत है",
    "Sign in to FraudShield": "FraudShield में साइन इन करें",
    "Sign in to access your FraudShield security dashboard.": "अपने FraudShield सुरक्षा डैशबोर्ड तक पहुँचने के लिए साइन इन करें।",
    "Full Name": "पूरा नाम",
    "Email Address": "ईमेल पता",
    "Email address": "ईमेल पता",
    "Password": "पासवर्ड",
    "Confirm Password": "पासवर्ड की पुष्टि करें",
    "Re-enter your password": "अपना पासवर्ड फिर से दर्ज करें",
    "Enter your full name": "अपना पूरा नाम दर्ज करें",
    "Enter your email address.": "अपना ईमेल पता दर्ज करें।",
    "Enter your password": "अपना पासवर्ड दर्ज करें",
    "Minimum 8 characters": "कम से कम 8 अक्षर",
    "Don't have an account?": "खाता नहीं है?",
    "Already have an account?": "पहले से खाता है?",
    "Please accept the terms before creating your account.": "खाता बनाने से पहले शर्तों को स्वीकार करें।",
    "Passwords do not match.": "पासवर्ड मेल नहीं खाते।",
    "Please enter a valid email address.": "कृपया मान्य ईमेल पता दर्ज करें।",
    "Please enter a valid transaction amount.": "कृपया मान्य लेनदेन राशि दर्ज करें।",
    "Account created successfully. Redirecting...": "खाता सफलतापूर्वक बनाया गया। रीडायरेक्ट किया जा रहा है...",
    "Sign In": "साइन इन",
    "Authenticated FraudShield account": "प्रमाणित FraudShield खाता",
    "JWT PROTECTED": "JWT सुरक्षित",
    "SECURE ANALYSIS": "सुरक्षित विश्लेषण",
    "FRAUDSHIELD AI · SOCIAL ENGINEERING DEFENSE": "FRAUDSHIELD AI · सोशल इंजीनियरिंग सुरक्षा",
    "Analyze suspicious conversations with explainable AI signals designed to detect OTP requests, impersonation, urgency and other social-engineering patterns.": "OTP अनुरोध, प्रतिरूपण, जल्दबाजी और अन्य सोशल-इंजीनियरिंग पैटर्न पहचानने के लिए समझाने योग्य AI संकेतों के साथ संदिग्ध बातचीत का विश्लेषण करें।",
    "Analyze suspicious conversations and detect social-engineering and voice-phishing signals before you share sensitive information.": "संवेदनशील जानकारी साझा करने से पहले संदिग्ध बातचीत का विश्लेषण करें और सोशल-इंजीनियरिंग व वॉइस-फ़िशिंग संकेत पहचानें।",
    "Detect urgency, impersonation, OTP requests and other social-engineering patterns.": "जल्दबाजी, प्रतिरूपण, OTP अनुरोध और अन्य सोशल-इंजीनियरिंग पैटर्न पहचानें।",
    "Detect OTP requests, bank impersonation, urgency and phone-scam signals.": "OTP अनुरोध, बैंक प्रतिरूपण, जल्दबाजी और फोन-स्कैम संकेत पहचानें।",
    "Enter a transcript on the left and run the AI analysis to see risk, confidence and detected indicators.": "जोखिम, विश्वास स्तर और पहचाने गए संकेत देखने के लिए बाईं ओर ट्रांसक्रिप्ट दर्ज करें और AI विश्लेषण चलाएँ।",
    "Use Chrome or Edge on localhost/HTTPS for live microphone transcription.": "लाइव माइक्रोफ़ोन ट्रांसक्रिप्शन के लिए localhost/HTTPS पर Chrome या Edge का उपयोग करें।",
    "Controlled browser-microphone detection. It analyzes captured speech; it does not automatically intercept cellular or WhatsApp calls.": "नियंत्रित ब्राउज़र-माइक्रोफ़ोन पहचान। यह रिकॉर्ड की गई स्पीच का विश्लेषण करती है; यह अपने आप मोबाइल या WhatsApp कॉल को इंटरसेप्ट नहीं करती।",
    "The system recommends the safest action based on the calculated risk.": "सिस्टम गणना किए गए जोखिम के आधार पर सबसे सुरक्षित कार्रवाई सुझाता है।",
    "Transaction, device and behavioural signals are analyzed in real time.": "लेनदेन, डिवाइस और व्यवहारिक संकेतों का रियल-टाइम में विश्लेषण किया जाता है।",
    "AI identifies suspicious patterns and explains the signals behind the risk score.": "AI संदिग्ध पैटर्न पहचानता है और जोखिम स्कोर के पीछे के संकेतों को समझाता है।",
    "Verify suspicious transactions without unnecessarily blocking legitimate payments.": "वैध भुगतान को अनावश्यक रूप से ब्लॉक किए बिना संदिग्ध लेनदेन सत्यापित करें।",
    "FraudShield combines transaction intelligence, behavioural analysis and AI-powered social engineering detection.": "FraudShield लेनदेन इंटेलिजेंस, व्यवहारिक विश्लेषण और AI-संचालित सोशल इंजीनियरिंग पहचान को जोड़ता है।",
    "Intelligent protection for the digital payment era.": "डिजिटल भुगतान युग के लिए बुद्धिमान सुरक्षा।",
    "No major suspicious signals were detected.": "कोई प्रमुख संदिग्ध संकेत नहीं मिले।",
    "No major suspicious pattern was detected in this transaction.": "इस लेनदेन में कोई प्रमुख संदिग्ध पैटर्न नहीं मिला।",
    "Additional verification is recommended.": "अतिरिक्त सत्यापन की सिफारिश की जाती है।",
    "Immediate investigation recommended.": "तुरंत जांच की सिफारिश की जाती है।",
    "Suspicious transaction detected.": "संदिग्ध लेनदेन पाया गया।",
    "Suspicious transaction detected by FraudShield AI.": "FraudShield AI ने संदिग्ध लेनदेन पाया।",
    "Amount unavailable": "राशि उपलब्ध नहीं है",
    "Recently": "हाल ही में",
    "Recently detected": "हाल ही में पाया गया",
    "Awaiting Risk Assessment": "जोखिम आकलन की प्रतीक्षा",
    "Awaiting analyst decision.": "विश्लेषक के निर्णय की प्रतीक्षा।",
    "Current behavior appears within the normal range.": "वर्तमान व्यवहार सामान्य सीमा में दिखाई देता है।",
    "Current score calculated from the available fraud and transaction signals.": "वर्तमान स्कोर उपलब्ध फ्रॉड और लेनदेन संकेतों से गणना किया गया है।",
    "Most frequently detected indicators.": "सबसे अधिक पाए गए संकेतक।",
    "Review behavioral risk, transaction history, fraud activity, devices and geographic risk for a user.": "उपयोगकर्ता के व्यवहारिक जोखिम, लेनदेन इतिहास, फ्रॉड गतिविधि, डिवाइस और भौगोलिक जोखिम की समीक्षा करें।",
    "No fraud alerts are currently associated with this user.": "इस उपयोगकर्ता से अभी कोई फ्रॉड अलर्ट जुड़ा नहीं है।",
    "Fraud events currently associated with this user.": "इस उपयोगकर्ता से वर्तमान में जुड़े फ्रॉड इवेंट।",
    "Transactions in last hour": "पिछले घंटे के लेनदेन",
    "Transactions prevented": "रोके गए लेनदेन",
    "Amount at Risk": "जोखिम में राशि",
    "Total network relationships:": "कुल नेटवर्क संबंध:",
    "Connections will appear after transactions contain network identifiers.": "लेनदेन में नेटवर्क पहचानकर्ता होने के बाद कनेक्शन दिखाई देंगे।",
    "Select an entity to inspect its connected relationships.": "इसके जुड़े संबंध देखने के लिए एक एंटिटी चुनें।",
    "ENTITY INVESTIGATION": "एंटिटी जांच",
    "ENTITY RELATIONSHIPS": "एंटिटी संबंध",
    "ENTITY TYPE": "एंटिटी प्रकार",
    "ENTITY ID": "एंटिटी ID",
    "RISK": "जोखिम",
    "Close": "बंद करें",
    "Inspect relationships connected to this entity.": "इस एंटिटी से जुड़े संबंधों की जांच करें।",
    "Loading...": "लोड हो रहा है...",
    "Building Fraud Network...": "फ्रॉड नेटवर्क बनाया जा रहा है...",
    "Loading users, transactions, devices, beneficiaries and locations.": "यूज़र, लेनदेन, डिवाइस, लाभार्थी और स्थान लोड हो रहे हैं।",
    "Refreshing...": "रिफ्रेश हो रहा है...",
    "Search Network Entities": "नेटवर्क एंटिटी खोजें",
    "Find suspicious devices, beneficiaries, locations or transactions quickly.": "संदिग्ध डिवाइस, लाभार्थी, स्थान या लेनदेन जल्दी खोजें।",
    "All relationships returned by the FraudShield network engine.": "FraudShield नेटवर्क इंजन द्वारा लौटाए गए सभी संबंध।",
    "NETWORK RISK": "नेटवर्क जोखिम",
    "Risk calculated from recent transactions and connected fraud entities.": "जोखिम की गणना हाल के लेनदेन और जुड़े फ्रॉड एंटिटी से की गई है।",
    "FRAUD INTELLIGENCE NETWORK": "फ्रॉड इंटेलिजेंस नेटवर्क",
    "FRAUDSHIELD SECURITY OPERATIONS CENTER": "फ्रॉडशील्ड सुरक्षा संचालन केंद्र",
    "Security Overview": "सुरक्षा अवलोकन",
    "Transaction Risk": "लेनदेन जोखिम",
    "Transaction Actions": "लेनदेन कार्रवाइयाँ",
    "Top Risk Signals": "शीर्ष जोखिम संकेत",
    "Fraud Intelligence Suite": "फ्रॉड इंटेलिजेंस सूट",
    "Transaction Security": "लेनदेन सुरक्षा",
    "Voice Phishing AI": "वॉइस फ़िशिंग AI",
    "Fraud Analyst Center": "फ्रॉड विश्लेषक केंद्र",
    "FraudShield Infrastructure": "FraudShield इंफ्रास्ट्रक्चर",
    "Security Operations": "सुरक्षा संचालन",
    "FRAUDSHIELD AI": "फ्रॉडशील्ड AI",
    "ADMIN": "एडमिन",
    "ADMIN ACCESS": "एडमिन एक्सेस",
    "AI ENGINE ONLINE": "AI इंजन ऑनलाइन",
    "AI ENGINE READY": "AI इंजन तैयार",
    "OPERATIONAL": "संचालित",
    "ACTIVE": "सक्रिय",
    "READY": "तैयार",
    "ONLINE": "ऑनलाइन",
    "LISTENING": "सुन रहा है",
    "LIVE": "लाइव",
    "HIGH": "उच्च",
    "MEDIUM": "मध्यम",
    "LOW": "कम",
    "NEW": "नया",
    "KNOWN": "ज्ञात",
    "UNKNOWN": "अज्ञात",
    "NORMAL": "सामान्य",
    "CHANGED": "बदला हुआ",
    "CONNECTED": "जुड़ा हुआ",
    "DETECTED": "पता चला",
    "SUSPICIOUS": "संदिग्ध",
    "PENDING": "लंबित",
    "REVIEWED": "समीक्षित",
    "ALLOWED": "अनुमत",
    "BLOCKED": "ब्लॉक किया गया",
    "ALLOW": "अनुमति दें",
    "BLOCK": "ब्लॉक करें",
    "REVIEW": "समीक्षा",
    "AMOUNT": "राशि",
    "AMOUNT AT RISK": "जोखिम में राशि",
    "RISK": "जोखिम",
    "STATUS": "स्थिति",
    "DECISION": "निर्णय",
    "ACTIONS": "कार्रवाइयाँ",
    "LOCATION": "स्थान",
    "LOCATIONS": "स्थान",
    "DEVICE": "डिवाइस",
    "DEVICES": "डिवाइस",
    "BENEFICIARY": "लाभार्थी",
    "BENEFICIARIES": "लाभार्थी",
    "CONNECTIONS": "कनेक्शन",
    "ENTITIES": "एंटिटी",
    "ENTITY": "एंटिटी",
    "TRANSACTION": "लेनदेन",
    "TRANSACTIONS": "लेनदेन",
    "ALERTS": "अलर्ट",
    "ANALYTICS": "एनालिटिक्स",
    "NETWORK": "नेटवर्क",
    "GEOGRAPHY": "भूगोल",
    "ADMIN": "एडमिन",
    "USERS": "यूज़र",
    "USER": "उपयोगकर्ता",
    "ANALYST": "विश्लेषक",
    "ANALYST FEEDBACK": "विश्लेषक प्रतिक्रिया",
    "ANALYST REVIEW": "विश्लेषक समीक्षा",
    "RISK DISTRIBUTION": "जोखिम वितरण",
    "RISK OVERVIEW": "जोखिम अवलोकन",
    "NETWORK TELEMETRY": "नेटवर्क टेलीमेट्री",
    "INTELLIGENCE COVERAGE": "इंटेलिजेंस कवरेज",
    "ENTITIES": "एंटिटी",
    "TRANSACTIONS": "लेनदेन",
    "DEVICES": "डिवाइस",
    "BENEFICIARIES": "लाभार्थी",
    "NETWORK EDGES": "नेटवर्क एज",
    "SUSPICIOUS": "संदिग्ध",
    "GEOGRAPHIC FRAUD INTELLIGENCE": "भौगोलिक फ्रॉड इंटेलिजेंस",
    "GEOGRAPHIC INTELLIGENCE": "भौगोलिक इंटेलिजेंस",
    "LIVE GEOGRAPHIC MONITORING": "लाइव भौगोलिक मॉनिटरिंग",
    "SYNC INTELLIGENCE": "इंटेलिजेंस सिंक करें",
    "SYNCING...": "सिंक हो रहा है...",
    "INVESTIGATION WORKFLOW": "जांच कार्यप्रवाह",
    "LOCATION RISK INTELLIGENCE": "स्थान जोखिम इंटेलिजेंस",
    "Observed Locations": "देखे गए स्थान",
    "Locations Requiring Attention": "ध्यान देने वाले स्थान",
    "Continue Investigation": "जांच जारी रखें",
    "Open Fraud Network": "फ्रॉड नेटवर्क खोलें",
    "Open Fraud Alerts": "फ्रॉड अलर्ट खोलें",
    "Device Intelligence": "डिवाइस इंटेलिजेंस",
    "Open Transaction Analyzer": "लेनदेन विश्लेषक खोलें",
    "Open Voice Detector": "वॉइस डिटेक्टर खोलें",
    "Search alerts...": "अलर्ट खोजें...",
    "Search device, beneficiary or identifier...": "डिवाइस, लाभार्थी या पहचानकर्ता खोजें...",
    "Search location, ID or city...": "स्थान, ID या शहर खोजें...",
    "Search transaction, risk or decision...": "लेनदेन, जोखिम या निर्णय खोजें...",
    "Search ID, name or location...": "ID, नाम या स्थान खोजें...",
    "Try changing your search or risk filter.": "अपनी खोज या जोखिम फ़िल्टर बदलकर देखें।",
    "Try a different search term or clear the filters.": "कोई दूसरा खोज शब्द आज़माएँ या फ़िल्टर साफ़ करें।",
    "View only": "केवल देखें",
    "Open Full Fraud Network": "पूरा फ्रॉड नेटवर्क खोलें",
    "Open Geography": "भूगोल खोलें",
    "Open Security Center": "सुरक्षा केंद्र खोलें",
    "Refresh Network": "नेटवर्क रिफ्रेश करें",
    "Sync Intelligence": "इंटेलिजेंस सिंक करें",
    "Synchronizing...": "सिंक्रोनाइज़ हो रहा है...",
    "Syncing Intelligence...": "इंटेलिजेंस सिंक हो रही है...",
  },
  or: {
    "FraudShield AI": "ଫ୍ରଡ୍‌ଶିଲ୍ଡ AI",
    "REAL-TIME FRAUD INTELLIGENCE": "ରିଅଲ୍-ଟାଇମ୍ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "Real-Time Transaction Protection": "ରିଅଲ୍-ଟାଇମ୍ ଲେନଦେନ ସୁରକ୍ଷା",
    "SECURE FRAUD INTELLIGENCE": "ସୁରକ୍ଷିତ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "FRAUDSHIELD SECURITY OPERATIONS CENTER": "ଫ୍ରଡ୍‌ଶିଲ୍ଡ ସୁରକ୍ଷା ଅପରେସନ୍ କେନ୍ଦ୍ର",
    "Fraud Intelligence Command Center": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ କମାଣ୍ଡ ସେଣ୍ଟର",
    "Fraud Alert Center": "ଠକେଇ ଆଲର୍ଟ କେନ୍ଦ୍ର",
    "FRAUD ALERT CENTER": "ଠକେଇ ଆଲର୍ଟ କେନ୍ଦ୍ର",
    "Fraud Intelligence Network": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ନେଟୱର୍କ",
    "Fraud Network": "ଠକେଇ ନେଟୱର୍କ",
    "Fraud Analytics": "ଠକେଇ ଆନାଲିଟିକ୍ସ",
    "Geographic Fraud": "ଭୌଗୋଳିକ ଠକେଇ",
    "Geographic Intelligence": "ଭୌଗୋଳିକ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "Device Intelligence": "ଡିଭାଇସ୍ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "DEVICE & BENEFICIARY INTELLIGENCE": "ଡିଭାଇସ୍ ଏବଂ ଲାଭାର୍ଥୀ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "BENEFICIARY INTELLIGENCE": "ଲାଭାର୍ଥୀ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "User Risk Profile": "ବ୍ୟବହାରକାରୀ ବିପଦ ପ୍ରୋଫାଇଲ୍",
    "USER RISK INTELLIGENCE": "ବ୍ୟବହାରକାରୀ ବିପଦ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "Voice Phishing Protection": "ଭଏସ୍ ଫିଶିଂ ସୁରକ୍ଷା",
    "Voice Phishing": "ଭଏସ୍ ଫିଶିଂ",
    "Voice Phishing AI": "ଭଏସ୍ ଫିଶିଂ AI",
    "Voice Analyzer": "ଭଏସ୍ ବିଶ୍ଳେଷକ",
    "Features": "ବୈଶିଷ୍ଟ୍ୟଗୁଡ଼ିକ",
    "Security": "ସୁରକ୍ଷା",
    "How It Works": "ଏହା କିପରି କାମ କରେ",
    "Back to Dashboard": "ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ",
    "Back to Login": "ଲଗଇନ୍‌କୁ ଫେରନ୍ତୁ",
    "Back to home": "ହୋମ୍‌କୁ ଫେରନ୍ତୁ",
    "Get Started": "ଆରମ୍ଭ କରନ୍ତୁ",
    "Login": "ଲଗଇନ୍",
    "Logout": "ଲଗଆଉଟ୍",
    "Register": "ପଞ୍ଜୀକରଣ",
    "Dashboard": "ଡ୍ୟାସବୋର୍ଡ",
    "Transaction": "ଲେନଦେନ",
    "Transactions": "ଲେନଦେନଗୁଡ଼ିକ",
    "Alerts": "ଆଲର୍ଟ",
    "Analytics": "ଆନାଲିଟିକ୍ସ",
    "Network": "ନେଟୱର୍କ",
    "Geography": "ଭୂଗୋଳ",
    "Devices": "ଡିଭାଇସ୍",
    "Beneficiaries": "ଲାଭାର୍ଥୀ",
    "Locations": "ସ୍ଥାନଗୁଡ଼ିକ",
    "Admin": "ଆଡମିନ୍",
    "Settings": "ସେଟିଂସ୍",
    "Real-Time Detection": "ରିଅଲ୍-ଟାଇମ୍ ଚିହ୍ନଟ",
    "Real-Time Monitoring": "ରିଅଲ୍-ଟାଇମ୍ ମନିଟରିଂ",
    "Explainable AI": "ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ AI",
    "Explainable Risk Signals": "ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ ବିପଦ ସଙ୍କେତ",
    "Explainable AI Decisions": "ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ AI ନିଷ୍ପତ୍ତି",
    "Privacy First": "ଗୋପନୀୟତା ପ୍ରଥମେ",
    "Powerful Protection": "ଶକ୍ତିଶାଳୀ ସୁରକ୍ଷା",
    "POWERFUL PROTECTION": "ଶକ୍ତିଶାଳୀ ସୁରକ୍ଷା",
    "Stop Fraud": "ଠକେଇ ରୋକନ୍ତୁ",
    "Before It Happens.": "ଘଟିବା ପୂର୍ବରୁ।",
    "Protect My Account": "ମୋ ଆକାଉଣ୍ଟକୁ ସୁରକ୍ଷିତ କରନ୍ତୁ",
    "See How It Works": "ଏହା କିପରି କାମ କରେ ଦେଖନ୍ତୁ",
    "AI-Powered Real-Time Protection": "AI-ଚାଳିତ ରିଅଲ୍-ଟାଇମ୍ ସୁରକ୍ଷା",
    "Suspicious Activity": "ସନ୍ଦେହଜନକ କାର୍ଯ୍ୟକଳାପ",
    "Suspicious activity": "ସନ୍ଦେହଜନକ କାର୍ଯ୍ୟକଳାପ",
    "Multiple unusual signals detected": "ଅନେକ ଅସାଧାରଣ ସଙ୍କେତ ଚିହ୍ନଟ ହୋଇଛି",
    "New beneficiary": "ନୂଆ ଲାଭାର୍ଥୀ",
    "New device": "ନୂଆ ଡିଭାଇସ୍",
    "Unusual amount": "ଅସାଧାରଣ ରାଶି",
    "Suspicious voice interaction": "ସନ୍ଦେହଜନକ ଭଏସ୍ ଇଣ୍ଟରାକ୍ସନ୍",
    "Review Transaction": "ଲେନଦେନ ସମୀକ୍ଷା କରନ୍ତୁ",
    "Review Status": "ସମୀକ୍ଷା ସ୍ଥିତି",
    "Review": "ସମୀକ୍ଷା",
    "Reviewed": "ସମୀକ୍ଷିତ",
    "Already Reviewed": "ପୂର୍ବରୁ ସମୀକ୍ଷିତ",
    "Mark as Reviewed": "ସମୀକ୍ଷିତ ଭାବେ ଚିହ୍ନଟ କରନ୍ତୁ",
    "Mark as read": "ପଢ଼ା ଭାବେ ଚିହ୍ନଟ କରନ୍ତୁ",
    "Mark Read": "ପଢ଼ା ଭାବେ ଚିହ୍ନଟ କରନ୍ତୁ",
    "High Risk": "ଉଚ୍ଚ ବିପଦ",
    "HIGH RISK": "ଉଚ୍ଚ ବିପଦ",
    "Medium Risk": "ମଧ୍ୟମ ବିପଦ",
    "MEDIUM RISK": "ମଧ୍ୟମ ବିପଦ",
    "Low Risk": "କମ୍ ବିପଦ",
    "LOW RISK": "କମ୍ ବିପଦ",
    "High": "ଉଚ୍ଚ",
    "Medium": "ମଧ୍ୟମ",
    "Low": "କମ୍",
    "Blocked": "ବ୍ଲକ୍ ହୋଇଛି",
    "Blocked Transactions": "ବ୍ଲକ୍ ହୋଇଥିବା ଲେନଦେନ",
    "Allowed": "ଅନୁମତିପ୍ରାପ୍ତ",
    "Needs Review": "ସମୀକ୍ଷା ଆବଶ୍ୟକ",
    "Pending": "ବକେୟା",
    "Confirmed": "ନିଶ୍ଚିତ",
    "Confirmed Fraud": "ନିଶ୍ଚିତ ଠକେଇ",
    "False Positive": "ଭୁଲ୍ ପଜିଟିଭ୍",
    "Human Review": "ମାନବୀୟ ସମୀକ୍ଷା",
    "Unread": "ଅପଢ଼ା",
    "No active alerts": "କୌଣସି ସକ୍ରିୟ ଆଲର୍ଟ ନାହିଁ",
    "No Fraud Alerts": "କୌଣସି ଠକେଇ ଆଲର୍ଟ ନାହିଁ",
    "No fraud alerts": "କୌଣସି ଠକେଇ ଆଲର୍ଟ ନାହିଁ",
    "No matching alerts": "କୌଣସି ମେଳ ଖାଉଥିବା ଆଲର୍ଟ ନାହିଁ",
    "No matching entities": "କୌଣସି ମେଳ ଖାଉଥିବା ଏଣ୍ଟିଟି ନାହିଁ",
    "No matching locations": "କୌଣସି ମେଳ ଖାଉଥିବା ସ୍ଥାନ ନାହିଁ",
    "No network data yet": "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ନେଟୱର୍କ ଡାଟା ନାହିଁ",
    "No relationships were found for this entity.": "ଏହି ଏଣ୍ଟିଟି ପାଇଁ କୌଣସି ସମ୍ପର୍କ ମିଳିଲା ନାହିଁ।",
    "No risk signals available.": "କୌଣସି ବିପଦ ସଙ୍କେତ ଉପଲବ୍ଧ ନାହିଁ।",
    "No risk signals detected": "କୌଣସି ବିପଦ ସଙ୍କେତ ମିଳିଲା ନାହିଁ",
    "No transactions available.": "କୌଣସି ଲେନଦେନ ଉପଲବ୍ଧ ନାହିଁ।",
    "No transactions found": "କୌଣସି ଲେନଦେନ ମିଳିଲା ନାହିଁ",
    "No devices found": "କୌଣସି ଡିଭାଇସ୍ ମିଳିଲା ନାହିଁ",
    "No beneficiaries found": "କୌଣସି ଲାଭାର୍ଥୀ ମିଳିଲେ ନାହିଁ",
    "No location data found": "କୌଣସି ସ୍ଥାନ ଡାଟା ମିଳିଲା ନାହିଁ",
    "No high-risk locations": "କୌଣସି ଉଚ୍ଚ ବିପଦ ସ୍ଥାନ ନାହିଁ",
    "Risk Assessment": "ବିପଦ ମୂଲ୍ୟାୟନ",
    "Overall Risk Score": "ମୋଟ ବିପଦ ସ୍କୋର୍",
    "RISK SCORE": "ବିପଦ ସ୍କୋର୍",
    "RISK LEVEL": "ବିପଦ ସ୍ତର",
    "OVERALL RISK": "ମୋଟ ବିପଦ",
    "Transaction Risk": "ଲେନଦେନ ବିପଦ",
    "Transaction Risk Analyzer": "ଲେନଦେନ ବିପଦ ବିଶ୍ଳେଷକ",
    "Transaction Actions": "ଲେନଦେନ କାର୍ଯ୍ୟ",
    "Transaction Context": "ଲେନଦେନ ପରିପ୍ରେକ୍ଷିତ",
    "Transaction Amount": "ଲେନଦେନ ରାଶି",
    "Transaction History": "ଲେନଦେନ ଇତିହାସ",
    "Recent Transactions": "ସମ୍ପ୍ରତିର ଲେନଦେନ",
    "Recent Fraud Alerts": "ସମ୍ପ୍ରତିର ଠକେଇ ଆଲର୍ଟ",
    "Top Risk Signals": "ମୁଖ୍ୟ ବିପଦ ସଙ୍କେତ",
    "Fraud Indicators": "ଠକେଇ ସୂଚକ",
    "Detected Signals": "ଚିହ୍ନଟ ହୋଇଥିବା ସଙ୍କେତ",
    "DETECTED SIGNALS": "ଚିହ୍ନଟ ହୋଇଥିବା ସଙ୍କେତ",
    "DETECTED PHISHING INDICATORS": "ଚିହ୍ନଟ ହୋଇଥିବା ଫିଶିଂ ସୂଚକ",
    "Why this score?": "ଏହି ସ୍କୋର୍ କାହିଁକି?",
    "WHY THIS DECISION?": "ଏହି ନିଷ୍ପତ୍ତି କାହିଁକି?",
    "Recommended Action": "ସୁପାରିଶ କରାଯାଇଥିବା କାର୍ଯ୍ୟ",
    "RECOMMENDED ACTION": "ସୁପାରିଶ କରାଯାଇଥିବା କାର୍ଯ୍ୟ",
    "Protect": "ସୁରକ୍ଷିତ କରନ୍ତୁ",
    "Analyze": "ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
    "Analyze Transaction": "ଲେନଦେନ ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
    "Analyzing...": "ବିଶ୍ଳେଷଣ ହେଉଛି...",
    "Retry": "ପୁନଃଚେଷ୍ଟା",
    "Try Again": "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
    "Refresh": "ରିଫ୍ରେଶ୍",
    "Refresh Intelligence": "ଇଣ୍ଟେଲିଜେନ୍ସ ରିଫ୍ରେଶ୍ କରନ୍ତୁ",
    "Refresh Alerts": "ଆଲର୍ଟ ରିଫ୍ରେଶ୍ କରନ୍ତୁ",
    "Refresh Network": "ନେଟୱର୍କ ରିଫ୍ରେଶ୍ କରନ୍ତୁ",
    "Refreshing...": "ରିଫ୍ରେଶ୍ ହେଉଛି...",
    "Reset Analysis": "ବିଶ୍ଳେଷଣ ରିସେଟ୍ କରନ୍ତୁ",
    "Search": "ଖୋଜନ୍ତୁ",
    "Search Network Entities": "ନେଟୱର୍କ ଏଣ୍ଟିଟି ଖୋଜନ୍ତୁ",
    "Search Geographic Entities": "ଭୌଗୋଳିକ ଏଣ୍ଟିଟି ଖୋଜନ୍ତୁ",
    "Clear": "ସଫା କରନ୍ତୁ",
    "Close": "ବନ୍ଦ କରନ୍ତୁ",
    "Dismiss": "ଖାରଜ କରନ୍ତୁ",
    "Investigate": "ତଦନ୍ତ କରନ୍ତୁ",
    "INVESTIGATE": "ତଦନ୍ତ କରନ୍ତୁ",
    "Investigation Tools": "ତଦନ୍ତ ଉପକରଣ",
    "INVESTIGATION TOOLS": "ତଦନ୍ତ ଉପକରଣ",
    "Investigation Workflow": "ତଦନ୍ତ କାର୍ଯ୍ୟପ୍ରବାହ",
    "Continue Investigation": "ତଦନ୍ତ ଜାରି ରଖନ୍ତୁ",
    "Open Alerts": "ଆଲର୍ଟ ଖୋଲନ୍ତୁ",
    "Open Fraud Alerts": "ଠକେଇ ଆଲର୍ଟ ଖୋଲନ୍ତୁ",
    "Open Fraud Network": "ଠକେଇ ନେଟୱର୍କ ଖୋଲନ୍ତୁ",
    "Open Geography": "ଭୂଗୋଳ ଖୋଲନ୍ତୁ",
    "Open Transaction Analyzer": "ଲେନଦେନ ବିଶ୍ଳେଷକ ଖୋଲନ୍ତୁ",
    "Open Voice Detector": "ଭଏସ୍ ଡିଟେକ୍ଟର ଖୋଲନ୍ତୁ",
    "View Alerts": "ଆଲର୍ଟ ଦେଖନ୍ତୁ",
    "View Analytics": "ଆନାଲିଟିକ୍ସ ଦେଖନ୍ତୁ",
    "View Risk Profile": "ବିପଦ ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ",
    "View Security Center": "ସୁରକ୍ଷା କେନ୍ଦ୍ର ଦେଖନ୍ତୁ",
    "Live Call Detection": "ଲାଇଭ୍ କଲ୍ ଚିହ୍ନଟ",
    "LIVE TRANSCRIPT": "ଲାଇଭ୍ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ",
    "CALL TRANSCRIPT": "କଲ୍ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ",
    "Conversation Analysis": "କଥୋପକଥନ ବିଶ୍ଳେଷଣ",
    "AI Assessment": "AI ମୂଲ୍ୟାୟନ",
    "Upload call recording": "କଲ୍ ରେକର୍ଡିଂ ଅପଲୋଡ୍ କରନ୍ତୁ",
    "OR PASTE TRANSCRIPT": "କିମ୍ବା ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ପେଷ୍ଟ୍ କରନ୍ତୁ",
    "Automatic AI analysis": "ସ୍ୱୟଂଚାଳିତ AI ବିଶ୍ଳେଷଣ",
    "Start Live Detection": "ଲାଇଭ୍ ଚିହ୍ନଟ ଆରମ୍ଭ କରନ୍ତୁ",
    "Stop Detection": "ଚିହ୍ନଟ ବନ୍ଦ କରନ୍ତୁ",
    "Awaiting conversation": "କଥୋପକଥନ ପାଇଁ ଅପେକ୍ଷା",
    "Waiting for speech": "ସ୍ପିଚ୍ ପାଇଁ ଅପେକ୍ଷା",
    "Voice Scam Detection": "ଭଏସ୍ ସ୍କାମ୍ ଚିହ୍ନଟ",
    "Analyze for Phishing": "ଫିଶିଂ ପାଇଁ ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
    "AI ENGINE ONLINE": "AI ଇଞ୍ଜିନ୍ ଅନଲାଇନ୍",
    "AI ENGINE READY": "AI ଇଞ୍ଜିନ୍ ପ୍ରସ୍ତୁତ",
    "Microphone active": "ମାଇକ୍ରୋଫୋନ୍ ସକ୍ରିୟ",
    "REAL-TIME FRAUD ENGINE": "ରିଅଲ୍-ଟାଇମ୍ ଠକେଇ ଇଞ୍ଜିନ୍",
    "AI CONFIDENCE": "AI ବିଶ୍ୱାସ ସ୍ତର",
    "AI DECISION": "AI ନିଷ୍ପତ୍ତି",
    "AI DECISIONS": "AI ନିଷ୍ପତ୍ତି",
    "AI EXPLAINABILITY": "AI ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟତା",
    "AI Explanation": "AI ବ୍ୟାଖ୍ୟା",
    "AI RISK LEVEL": "AI ବିପଦ ସ୍ତର",
    "Rule evaluation": "ନିୟମ ମୂଲ୍ୟାୟନ",
    "ML risk scoring": "ML ବିପଦ ସ୍କୋରିଂ",
    "Machine Learning": "ମେସିନ୍ ଲର୍ଣ୍ଣିଂ",
    "Signals Used by the Engine": "ଇଞ୍ଜିନ୍ ଦ୍ୱାରା ବ୍ୟବହୃତ ସଙ୍କେତ",
    "BEHAVIORAL SECURITY SIGNALS": "ବ୍ୟବହାରିକ ସୁରକ୍ଷା ସଙ୍କେତ",
    "BEHAVIORAL RISK": "ବ୍ୟବହାରିକ ବିପଦ",
    "FRAUD INTELLIGENCE": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "FRAUD INVESTIGATION": "ଠକେଇ ତଦନ୍ତ",
    "ENTERPRISE FRAUD INTELLIGENCE": "ଏଣ୍ଟରପ୍ରାଇଜ୍ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "SECURITY OPERATIONS": "ସୁରକ୍ଷା ଅପରେସନ୍",
    "SECURITY MONITORING": "ସୁରକ୍ଷା ମନିଟରିଂ",
    "SECURITY OVERVIEW": "ସୁରକ୍ଷା ଅବଲୋକନ",
    "LIVE SECURITY ALERTS": "ଲାଇଭ୍ ସୁରକ୍ଷା ଆଲର୍ଟ",
    "LIVE FRAUD EVENT": "ଲାଇଭ୍ ଠକେଇ ଘଟଣା",
    "LIVE TELEMETRY": "ଲାଇଭ୍ ଟେଲିମେଟ୍ରି",
    "LIVE MONITORING": "ଲାଇଭ୍ ମନିଟରିଂ",
    "LIVE NETWORK": "ଲାଇଭ୍ ନେଟୱର୍କ",
    "ALL SYSTEMS OPERATIONAL": "ସମସ୍ତ ସିଷ୍ଟମ୍ ସକ୍ରିୟ ଅଛି",
    "Protection active": "ସୁରକ୍ଷା ସକ୍ରିୟ",
    "Loaded from backend": "ବ୍ୟାକଏଣ୍ଡରୁ ଲୋଡ୍ ହୋଇଛି",
    "Loading fraud alerts": "ଠକେଇ ଆଲର୍ଟ ଲୋଡ୍ ହେଉଛି",
    "Loading fraud alerts...": "ଠକେଇ ଆଲର୍ଟ ଲୋଡ୍ ହେଉଛି...",
    "Loading Fraud Intelligence": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହେଉଛି",
    "Loading fraud intelligence...": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହେଉଛି...",
    "Loading intelligence...": "ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହେଉଛି...",
    "Loading geographic intelligence": "ଭୌଗୋଳିକ ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହେଉଛି",
    "Loading users, transactions, devices, beneficiaries and locations.": "ବ୍ୟବହାରକାରୀ, ଲେନଦେନ, ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ ଏବଂ ସ୍ଥାନ ଲୋଡ୍ ହେଉଛି।",
    "Connecting to fraud detection engine...": "ଠକେଇ ଚିହ୍ନଟ ଇଞ୍ଜିନ୍ ସହିତ ସଂଯୋଗ ହେଉଛି...",
    "Connecting to the FraudShield backend.": "FraudShield ବ୍ୟାକଏଣ୍ଡ ସହିତ ସଂଯୋଗ ହେଉଛି।",
    "Intelligence engine unavailable": "ଇଣ୍ଟେଲିଜେନ୍ସ ଇଞ୍ଜିନ୍ ଉପଲବ୍ଧ ନାହିଁ",
    "Intelligence service error": "ଇଣ୍ଟେଲିଜେନ୍ସ ସେବା ତ୍ରୁଟି",
    "Unable to load alerts": "ଆଲର୍ଟ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ",
    "Unable to load analytics": "ଆନାଲିଟିକ୍ସ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ",
    "Unable to load fraud alerts.": "ଠକେଇ ଆଲର୍ଟ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
    "Unable to load fraud analytics.": "ଠକେଇ ଆନାଲିଟିକ୍ସ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
    "Unable to load device and beneficiary intelligence.": "ଡିଭାଇସ୍ ଏବଂ ଲାଭାର୍ଥୀ ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
    "Unable to load geographic fraud intelligence.": "ଭୌଗୋଳିକ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
    "Unable to load user risk profile.": "ବ୍ୟବହାରକାରୀ ବିପଦ ପ୍ରୋଫାଇଲ୍ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
    "Admin Controls": "ଆଡମିନ୍ ନିୟନ୍ତ୍ରଣ",
    "Alert Management": "ଆଲର୍ଟ ପରିଚାଳନା",
    "Analyst Center": "ବିଶ୍ଳେଷକ କେନ୍ଦ୍ର",
    "Analyst Review": "ବିଶ୍ଳେଷକ ସମୀକ୍ଷା",
    "Analyst Feedback": "ବିଶ୍ଳେଷକ ପ୍ରତିକ୍ରିୟା",
    "Total Alerts": "ମୋଟ ଆଲର୍ଟ",
    "TOTAL ALERTS": "ମୋଟ ଆଲର୍ଟ",
    "UNREAD ALERTS": "ଅପଢ଼ା ଆଲର୍ଟ",
    "AMOUNT AT RISK": "ବିପଦରେ ଥିବା ରାଶି",
    "AVERAGE RISK": "ହାରାହାରି ବିପଦ",
    "TOTAL TRANSACTIONS": "ମୋଟ ଲେନଦେନ",
    "Total Transactions": "ମୋଟ ଲେନଦେନ",
    "Total Devices": "ମୋଟ ଡିଭାଇସ୍",
    "Known Devices": "ଜଣାଶୁଣା ଡିଭାଇସ୍",
    "Known Beneficiaries": "ଜଣାଶୁଣା ଲାଭାର୍ଥୀ",
    "Connections": "ସଂଯୋଗ",
    "Network relationships": "ନେଟୱର୍କ ସମ୍ପର୍କ",
    "NETWORK CONNECTIONS": "ନେଟୱର୍କ ସଂଯୋଗ",
    "NETWORK CONTEXT": "ନେଟୱର୍କ ପରିପ୍ରେକ୍ଷିତ",
    "NETWORK EDGES": "ନେଟୱର୍କ ଏଜ୍",
    "NETWORK RISK": "ନେଟୱର୍କ ବିପଦ",
    "All Risk Levels": "ସମସ୍ତ ବିପଦ ସ୍ତର",
    "All Types": "ସମସ୍ତ ପ୍ରକାର",
    "All": "ସମସ୍ତ",
    "High risk transactions": "ଉଚ୍ଚ ବିପଦ ଲେନଦେନ",
    "High-risk transactions": "ଉଚ୍ଚ ବିପଦ ଲେନଦେନ",
    "High-risk locations should be investigated alongside transaction and device signals.": "ଉଚ୍ଚ ବିପଦ ସ୍ଥାନଗୁଡ଼ିକୁ ଲେନଦେନ ଏବଂ ଡିଭାଇସ୍ ସଙ୍କେତ ସହିତ ତଦନ୍ତ କରାଯିବା ଉଚିତ।",
    "Risk calculated from recent transactions and connected fraud entities.": "ସମ୍ପ୍ରତିର ଲେନଦେନ ଏବଂ ସଂଯୁକ୍ତ ଠକେଇ ଏଣ୍ଟିଟିରୁ ବିପଦ ଗଣନା କରାଯାଇଛି।",
    "Review the transaction risk signals associated with this user.": "ଏହି ବ୍ୟବହାରକାରୀ ସହିତ ସଂପୃକ୍ତ ଲେନଦେନ ବିପଦ ସଙ୍କେତ ସମୀକ୍ଷା କରନ୍ତୁ।",
    "Consolidated behavioral intelligence across transactions, devices, beneficiaries, locations and fraud alerts.": "ଲେନଦେନ, ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ, ସ୍ଥାନ ଏବଂ ଠକେଇ ଆଲର୍ଟର ସଂଯୁକ୍ତ ବ୍ୟବହାରିକ ଇଣ୍ଟେଲିଜେନ୍ସ।",
    "Review suspicious transactions, alerts and AI fraud decisions.": "ସନ୍ଦେହଜନକ ଲେନଦେନ, ଆଲର୍ଟ ଏବଂ AI ଠକେଇ ନିଷ୍ପତ୍ତି ସମୀକ୍ଷା କରନ୍ତୁ।",
    "Review individual transaction decisions and risk scores.": "ବ୍ୟକ୍ତିଗତ ଲେନଦେନ ନିଷ୍ପତ୍ତି ଏବଂ ବିପଦ ସ୍କୋର ସମୀକ୍ଷା କରନ୍ତୁ।",
    "Monitor suspicious transactions and investigate real-time fraud signals.": "ସନ୍ଦେହଜନକ ଲେନଦେନ ମନିଟର କରନ୍ତୁ ଏବଂ ରିଅଲ୍-ଟାଇମ୍ ଠକେଇ ସଙ୍କେତ ତଦନ୍ତ କରନ୍ତୁ।",
    "Monitor suspicious transactions, investigate fraud alerts and review AI decisions.": "ସନ୍ଦେହଜନକ ଲେନଦେନ ମନିଟର କରନ୍ତୁ, ଠକେଇ ଆଲର୍ଟ ତଦନ୍ତ କରନ୍ତୁ ଏବଂ AI ନିଷ୍ପତ୍ତି ସମୀକ୍ଷା କରନ୍ତୁ।",
    "Filter and review suspicious transactions detected by FraudShield AI.": "FraudShield AI ଦ୍ୱାରା ଚିହ୍ନଟ ସନ୍ଦେହଜନକ ଲେନଦେନ ଫିଲ୍ଟର୍ ଏବଂ ସମୀକ୍ଷା କରନ୍ତୁ।",
    "Analyze UPI transactions using behavioral signals and AI-powered fraud detection.": "ବ୍ୟବହାରିକ ସଙ୍କେତ ଏବଂ AI-ଚାଳିତ ଠକେଇ ଚିହ୍ନଟ ବ୍ୟବହାର କରି UPI ଲେନଦେନ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।",
    "Analyze transaction locations and suspicious geographic activity.": "ଲେନଦେନ ସ୍ଥାନ ଏବଂ ସନ୍ଦେହଜନକ ଭୌଗୋଳିକ କାର୍ଯ୍ୟକଳାପ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।",
    "Analyze transactions with device, beneficiary or location identifiers to build the network.": "ନେଟୱର୍କ ତିଆରି ପାଇଁ ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ କିମ୍ବା ସ୍ଥାନ ପରିଚୟକର୍ତ୍ତା ସହିତ ଲେନଦେନ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।",
    "Analyze device behavior, suspicious sessions and transaction-device relationships.": "ଡିଭାଇସ୍ ବ୍ୟବହାର, ସନ୍ଦେହଜନକ ସେସନ୍ ଏବଂ ଲେନଦେନ-ଡିଭାଇସ୍ ସମ୍ପର୍କ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।",
    "Find suspicious devices and beneficiaries quickly.": "ସନ୍ଦେହଜନକ ଡିଭାଇସ୍ ଏବଂ ଲାଭାର୍ଥୀଙ୍କୁ ଶୀଘ୍ର ଖୋଜନ୍ତୁ।",
    "Find suspicious devices, beneficiaries, locations or transactions quickly.": "ସନ୍ଦେହଜନକ ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ, ସ୍ଥାନ କିମ୍ବା ଲେନଦେନକୁ ଶୀଘ୍ର ଖୋଜନ୍ତୁ।",
    "Find suspicious locations and investigate their network relationships.": "ସନ୍ଦେହଜନକ ସ୍ଥାନ ଖୋଜନ୍ତୁ ଏବଂ ସେମାନଙ୍କ ନେଟୱର୍କ ସମ୍ପର୍କ ତଦନ୍ତ କରନ୍ତୁ।",
    "See how devices and beneficiaries relate to transactions and locations.": "ଡିଭାଇସ୍ ଏବଂ ଲାଭାର୍ଥୀ ଲେନଦେନ ଏବଂ ସ୍ଥାନ ସହିତ କିପରି ସଂପୃକ୍ତ ତାହା ଦେଖନ୍ତୁ।",
    "Beneficiaries connected to your transaction network.": "ଆପଣଙ୍କ ଲେନଦେନ ନେଟୱର୍କ ସହିତ ସଂଯୁକ୍ତ ଲାଭାର୍ଥୀ।",
    "Devices connected to your stored transaction network.": "ଆପଣଙ୍କ ସଞ୍ଚିତ ଲେନଦେନ ନେଟୱର୍କ ସହିତ ସଂଯୁକ୍ତ ଡିଭାଇସ୍।",
    "Fraud network intelligence is connected to the live backend.": "ଠକେଇ ନେଟୱର୍କ ଇଣ୍ଟେଲିଜେନ୍ସ ଲାଇଭ୍ ବ୍ୟାକଏଣ୍ଡ ସହିତ ସଂଯୁକ୍ତ।",
    "FraudShield is analyzing your fraud-network entities.": "FraudShield ଆପଣଙ୍କ ଠକେଇ-ନେଟୱର୍କ ଏଣ୍ଟିଟିଗୁଡ଼ିକୁ ବିଶ୍ଳେଷଣ କରୁଛି।",
    "Known network devices": "ଜଣାଶୁଣା ନେଟୱର୍କ ଡିଭାଇସ୍",
    "Connected destinations": "ସଂଯୁକ୍ତ ଗନ୍ତବ୍ୟସ୍ଥଳ",
    "Entities requiring attention": "ଧ୍ୟାନ ଆବଶ୍ୟକ କରୁଥିବା ଏଣ୍ଟିଟି",
    "Geographic entities": "ଭୌଗୋଳିକ ଏଣ୍ଟିଟି",
    "Geographic entities connected to your fraud intelligence network.": "ଆପଣଙ୍କ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ନେଟୱର୍କ ସହିତ ସଂଯୁକ୍ତ ଭୌଗୋଳିକ ଏଣ୍ଟିଟି।",
    "Geographic Risk Distribution": "ଭୌଗୋଳିକ ବିପଦ ବଣ୍ଟନ",
    "Geographic Signals": "ଭୌଗୋଳିକ ସଙ୍କେତ",
    "LOCATION RISK INTELLIGENCE": "ସ୍ଥାନ ବିପଦ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "LOCATION INVESTIGATION": "ସ୍ଥାନ ତଦନ୍ତ",
    "Locations Requiring Attention": "ଧ୍ୟାନ ଆବଶ୍ୟକ କରୁଥିବା ସ୍ଥାନ",
    "Observed Locations": "ପର୍ଯ୍ୟବେକ୍ଷିତ ସ୍ଥାନ",
    "No high-risk locations": "କୌଣସି ଉଚ୍ଚ ବିପଦ ସ୍ଥାନ ନାହିଁ",
    "Geographic intelligence currently shows no high-risk locations.": "ଭୌଗୋଳିକ ଇଣ୍ଟେଲିଜେନ୍ସରେ ବର୍ତ୍ତମାନ କୌଣସି ଉଚ୍ଚ ବିପଦ ସ୍ଥାନ ଦେଖାଯାଉନାହିଁ।",
    "Geographic intelligence error:": "ଭୌଗୋଳିକ ଇଣ୍ଟେଲିଜେନ୍ସ ତ୍ରୁଟି:",
    "Create Secure Account": "ସୁରକ୍ଷିତ ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ",
    "Create a FraudShield account": "FraudShield ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ",
    "Create your account": "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ",
    "Creating Account...": "ଆକାଉଣ୍ଟ ତିଆରି ହେଉଛି...",
    "Welcome back": "ପୁଣି ସ୍ୱାଗତ",
    "Sign in to FraudShield": "FraudShield ରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
    "Sign in to access your FraudShield security dashboard.": "ଆପଣଙ୍କ FraudShield ସୁରକ୍ଷା ଡ୍ୟାସବୋର୍ଡ ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।",
    "Full Name": "ପୂର୍ଣ୍ଣ ନାମ",
    "Email Address": "ଇମେଲ୍ ଠିକଣା",
    "Email address": "ଇମେଲ୍ ଠିକଣା",
    "Password": "ପାସୱାର୍ଡ",
    "Confirm Password": "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "Re-enter your password": "ପାସୱାର୍ଡ ପୁଣି ଦିଅନ୍ତୁ",
    "Enter your full name": "ଆପଣଙ୍କ ପୂର୍ଣ୍ଣ ନାମ ଦିଅନ୍ତୁ",
    "Enter your email address.": "ଆପଣଙ୍କ ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ।",
    "Enter your password": "ଆପଣଙ୍କ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ",
    "Minimum 8 characters": "ଅତି କମରେ ୮ଟି ଅକ୍ଷର",
    "Don't have an account?": "ଆକାଉଣ୍ଟ ନାହିଁ କି?",
    "Already have an account?": "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ ଅଛି କି?",
    "Please accept the terms before creating your account.": "ଆକାଉଣ୍ଟ ତିଆରି କରିବା ପୂର୍ବରୁ ନିୟମଗୁଡ଼ିକୁ ଗ୍ରହଣ କରନ୍ତୁ।",
    "Passwords do not match.": "ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ।",
    "Please enter a valid email address.": "ଦୟାକରି ଏକ ବୈଧ ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ।",
    "Please enter a valid transaction amount.": "ଦୟାକରି ଏକ ବୈଧ ଲେନଦେନ ରାଶି ଦିଅନ୍ତୁ।",
    "Account created successfully. Redirecting...": "ଆକାଉଣ୍ଟ ସଫଳତାର ସହିତ ତିଆରି ହୋଇଛି। ରିଡାଇରେକ୍ଟ ହେଉଛି...",
    "Sign In": "ସାଇନ୍ ଇନ୍",
    "Authenticated FraudShield account": "ପ୍ରମାଣିତ FraudShield ଆକାଉଣ୍ଟ",
    "JWT PROTECTED": "JWT ସୁରକ୍ଷିତ",
    "SECURE ANALYSIS": "ସୁରକ୍ଷିତ ବିଶ୍ଳେଷଣ",
    "FRAUDSHIELD AI · SOCIAL ENGINEERING DEFENSE": "FRAUDSHIELD AI · ସୋସିଆଲ୍ ଇଞ୍ଜିନିୟରିଂ ସୁରକ୍ଷା",
    "Analyze suspicious conversations with explainable AI signals designed to detect OTP requests, impersonation, urgency and other social-engineering patterns.": "OTP ଅନୁରୋଧ, ଛଦ୍ମବେଶ, ଜରୁରୀକାଳୀନତା ଏବଂ ଅନ୍ୟ ସୋସିଆଲ୍ ଇଞ୍ଜିନିୟରିଂ ପ୍ୟାଟର୍ନ ଚିହ୍ନଟ ପାଇଁ ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ AI ସଙ୍କେତ ସହିତ ସନ୍ଦେହଜନକ କଥୋପକଥନ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।",
    "Analyze suspicious conversations and detect social-engineering and voice-phishing signals before you share sensitive information.": "ସମ୍ବେଦନଶୀଳ ସୂଚନା ସେୟାର୍ କରିବା ପୂର୍ବରୁ ସନ୍ଦେହଜନକ କଥୋପକଥନ ବିଶ୍ଳେଷଣ କରନ୍ତୁ ଏବଂ ସୋସିଆଲ୍ ଇଞ୍ଜିନିୟରିଂ ଓ ଭଏସ୍ ଫିଶିଂ ସଙ୍କେତ ଚିହ୍ନଟ କରନ୍ତୁ।",
    "Detect urgency, impersonation, OTP requests and other social-engineering patterns.": "ଜରୁରୀକାଳୀନତା, ଛଦ୍ମବେଶ, OTP ଅନୁରୋଧ ଏବଂ ଅନ୍ୟ ସୋସିଆଲ୍ ଇଞ୍ଜିନିୟରିଂ ପ୍ୟାଟର୍ନ ଚିହ୍ନଟ କରନ୍ତୁ।",
    "Detect OTP requests, bank impersonation, urgency and phone-scam signals.": "OTP ଅନୁରୋଧ, ବ୍ୟାଙ୍କ ଛଦ୍ମବେଶ, ଜରୁରୀକାଳୀନତା ଏବଂ ଫୋନ୍ ସ୍କାମ୍ ସଙ୍କେତ ଚିହ୍ନଟ କରନ୍ତୁ।",
    "Enter a transcript on the left and run the AI analysis to see risk, confidence and detected indicators.": "ବିପଦ, ବିଶ୍ୱାସ ସ୍ତର ଏବଂ ଚିହ୍ନଟ ସୂଚକ ଦେଖିବା ପାଇଁ ବାମପଟେ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ଦିଅନ୍ତୁ ଏବଂ AI ବିଶ୍ଳେଷଣ ଚଲାନ୍ତୁ।",
    "Use Chrome or Edge on localhost/HTTPS for live microphone transcription.": "ଲାଇଭ୍ ମାଇକ୍ରୋଫୋନ୍ ଟ୍ରାନ୍ସକ୍ରିପ୍ସନ୍ ପାଇଁ localhost/HTTPS ରେ Chrome କିମ୍ବା Edge ବ୍ୟବହାର କରନ୍ତୁ।",
    "The system recommends the safest action based on the calculated risk.": "ଗଣନା କରାଯାଇଥିବା ବିପଦ ଆଧାରରେ ସିଷ୍ଟମ୍ ସବୁଠାରୁ ସୁରକ୍ଷିତ କାର୍ଯ୍ୟ ସୁପାରିଶ କରେ।",
    "Transaction, device and behavioural signals are analyzed in real time.": "ଲେନଦେନ, ଡିଭାଇସ୍ ଏବଂ ବ୍ୟବହାରିକ ସଙ୍କେତଗୁଡ଼ିକୁ ରିଅଲ୍-ଟାଇମ୍‌ରେ ବିଶ୍ଳେଷଣ କରାଯାଏ।",
    "AI identifies suspicious patterns and explains the signals behind the risk score.": "AI ସନ୍ଦେହଜନକ ପ୍ୟାଟର୍ନ ଚିହ୍ନଟ କରେ ଏବଂ ବିପଦ ସ୍କୋର୍ ପଛର ସଙ୍କେତଗୁଡ଼ିକୁ ବ୍ୟାଖ୍ୟା କରେ।",
    "Verify suspicious transactions without unnecessarily blocking legitimate payments.": "ବୈଧ ପେମେଣ୍ଟକୁ ଅନାବଶ୍ୟକ ଭାବରେ ବ୍ଲକ୍ ନକରି ସନ୍ଦେହଜନକ ଲେନଦେନ ଯାଞ୍ଚ କରନ୍ତୁ।",
    "FraudShield combines transaction intelligence, behavioural analysis and AI-powered social engineering detection.": "FraudShield ଲେନଦେନ ଇଣ୍ଟେଲିଜେନ୍ସ, ବ୍ୟବହାରିକ ବିଶ୍ଳେଷଣ ଏବଂ AI-ଚାଳିତ ସୋସିଆଲ୍ ଇଞ୍ଜିନିୟରିଂ ଚିହ୍ନଟକୁ ଏକତ୍ର କରେ।",
    "Intelligent protection for the digital payment era.": "ଡିଜିଟାଲ୍ ପେମେଣ୍ଟ ଯୁଗ ପାଇଁ ବୁଦ୍ଧିମାନ ସୁରକ୍ଷା।",
    "No major suspicious signals were detected.": "କୌଣସି ପ୍ରମୁଖ ସନ୍ଦେହଜନକ ସଙ୍କେତ ମିଳିଲା ନାହିଁ।",
    "Additional verification is recommended.": "ଅତିରିକ୍ତ ଯାଞ୍ଚ ସୁପାରିଶ କରାଯାଏ।",
    "Immediate investigation recommended.": "ତୁରନ୍ତ ତଦନ୍ତ ସୁପାରିଶ କରାଯାଏ।",
    "Suspicious transaction detected.": "ସନ୍ଦେହଜନକ ଲେନଦେନ ଚିହ୍ନଟ ହୋଇଛି।",
    "Suspicious transaction detected by FraudShield AI.": "FraudShield AI ସନ୍ଦେହଜନକ ଲେନଦେନ ଚିହ୍ନଟ କରିଛି।",
    "Amount unavailable": "ରାଶି ଉପଲବ୍ଧ ନାହିଁ",
    "Recently": "ସମ୍ପ୍ରତି",
    "Recently detected": "ସମ୍ପ୍ରତି ଚିହ୍ନଟ",
    "Awaiting Risk Assessment": "ବିପଦ ମୂଲ୍ୟାୟନ ପାଇଁ ଅପେକ୍ଷା",
    "Awaiting analyst decision.": "ବିଶ୍ଳେଷକ ନିଷ୍ପତ୍ତି ପାଇଁ ଅପେକ୍ଷା।",
    "Current behavior appears within the normal range.": "ବର୍ତ୍ତମାନର ବ୍ୟବହାର ସାଧାରଣ ସୀମା ମଧ୍ୟରେ ଦେଖାଯାଉଛି।",
    "Current score calculated from the available fraud and transaction signals.": "ଉପଲବ୍ଧ ଠକେଇ ଏବଂ ଲେନଦେନ ସଙ୍କେତରୁ ବର୍ତ୍ତମାନ ସ୍କୋର୍ ଗଣନା କରାଯାଇଛି।",
    "Most frequently detected indicators.": "ସର୍ବାଧିକ ଚିହ୍ନଟ ହୋଇଥିବା ସୂଚକଗୁଡ଼ିକ।",
    "Review behavioral risk, transaction history, fraud activity, devices and geographic risk for a user.": "ବ୍ୟବହାରକାରୀଙ୍କ ବ୍ୟବହାରିକ ବିପଦ, ଲେନଦେନ ଇତିହାସ, ଠକେଇ କାର୍ଯ୍ୟକଳାପ, ଡିଭାଇସ୍ ଏବଂ ଭୌଗୋଳିକ ବିପଦ ସମୀକ୍ଷା କରନ୍ତୁ।",
    "No fraud alerts are currently associated with this user.": "ଏହି ବ୍ୟବହାରକାରୀ ସହିତ ବର୍ତ୍ତମାନ କୌଣସି ଠକେଇ ଆଲର୍ଟ ସଂପୃକ୍ତ ନାହିଁ।",
    "Fraud events currently associated with this user.": "ଏହି ବ୍ୟବହାରକାରୀ ସହିତ ବର୍ତ୍ତମାନ ସଂପୃକ୍ତ ଠକେଇ ଘଟଣାଗୁଡ଼ିକ।",
    "Transactions in last hour": "ଗତ ଏକ ଘଣ୍ଟାରେ ଲେନଦେନ",
    "Transactions prevented": "ରୋକାଯାଇଥିବା ଲେନଦେନ",
    "Amount at Risk": "ବିପଦରେ ଥିବା ରାଶି",
    "Total network relationships:": "ମୋଟ ନେଟୱର୍କ ସମ୍ପର୍କ:",
    "Connections will appear after transactions contain network identifiers.": "ଲେନଦେନରେ ନେଟୱର୍କ ପରିଚୟକର୍ତ୍ତା ଥିଲେ ସଂଯୋଗଗୁଡ଼ିକ ଦେଖାଯିବ।",
    "Select an entity to inspect its connected relationships.": "ଏହାର ସଂଯୁକ୍ତ ସମ୍ପର୍କ ଯାଞ୍ଚ କରିବାକୁ ଏକ ଏଣ୍ଟିଟି ବାଛନ୍ତୁ।",
    "ENTITY INVESTIGATION": "ଏଣ୍ଟିଟି ତଦନ୍ତ",
    "ENTITY RELATIONSHIPS": "ଏଣ୍ଟିଟି ସମ୍ପର୍କ",
    "ENTITY TYPE": "ଏଣ୍ଟିଟି ପ୍ରକାର",
    "ENTITY ID": "ଏଣ୍ଟିଟି ID",
    "RISK": "ବିପଦ",
    "Inspect relationships connected to this entity.": "ଏହି ଏଣ୍ଟିଟି ସହିତ ସଂଯୁକ୍ତ ସମ୍ପର୍କ ଯାଞ୍ଚ କରନ୍ତୁ।",
    "Loading...": "ଲୋଡ୍ ହେଉଛି...",
    "Building Fraud Network...": "ଠକେଇ ନେଟୱର୍କ ତିଆରି ହେଉଛି...",
    "Loading users, transactions, devices, beneficiaries and locations.": "ବ୍ୟବହାରକାରୀ, ଲେନଦେନ, ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ ଏବଂ ସ୍ଥାନ ଲୋଡ୍ ହେଉଛି।",
    "Refreshing...": "ରିଫ୍ରେଶ୍ ହେଉଛି...",
    "Search Network Entities": "ନେଟୱର୍କ ଏଣ୍ଟିଟି ଖୋଜନ୍ତୁ",
    "Find suspicious devices, beneficiaries, locations or transactions quickly.": "ସନ୍ଦେହଜନକ ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ, ସ୍ଥାନ କିମ୍ବା ଲେନଦେନକୁ ଶୀଘ୍ର ଖୋଜନ୍ତୁ।",
    "All relationships returned by the FraudShield network engine.": "FraudShield ନେଟୱର୍କ ଇଞ୍ଜିନ୍ ଦ୍ୱାରା ଫେରାଯାଇଥିବା ସମସ୍ତ ସମ୍ପର୍କ।",
    "NETWORK RISK": "ନେଟୱର୍କ ବିପଦ",
    "Risk calculated from recent transactions and connected fraud entities.": "ସମ୍ପ୍ରତିର ଲେନଦେନ ଏବଂ ସଂଯୁକ୍ତ ଠକେଇ ଏଣ୍ଟିଟିରୁ ବିପଦ ଗଣନା କରାଯାଇଛି।",
    "FRAUD INTELLIGENCE NETWORK": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ନେଟୱର୍କ",
    "Security Overview": "ସୁରକ୍ଷା ଅବଲୋକନ",
    "Transaction Risk": "ଲେନଦେନ ବିପଦ",
    "Transaction Actions": "ଲେନଦେନ କାର୍ଯ୍ୟ",
    "Top Risk Signals": "ମୁଖ୍ୟ ବିପଦ ସଙ୍କେତ",
    "Fraud Intelligence Suite": "ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ ସୁଇଟ୍",
    "Transaction Security": "ଲେନଦେନ ସୁରକ୍ଷା",
    "Fraud Analyst Center": "ଠକେଇ ବିଶ୍ଳେଷକ କେନ୍ଦ୍ର",
    "FraudShield Infrastructure": "FraudShield ଇନ୍‌ଫ୍ରାସ୍ଟ୍ରକ୍ଚର୍",
    "Security Operations": "ସୁରକ୍ଷା ଅପରେସନ୍",
    "ADMIN ACCESS": "ଆଡମିନ୍ ଆକ୍ସେସ୍",
    "AI ENGINE ONLINE": "AI ଇଞ୍ଜିନ୍ ଅନଲାଇନ୍",
    "AI ENGINE READY": "AI ଇଞ୍ଜିନ୍ ପ୍ରସ୍ତୁତ",
    "OPERATIONAL": "ସକ୍ରିୟ",
    "ACTIVE": "ସକ୍ରିୟ",
    "READY": "ପ୍ରସ୍ତୁତ",
    "ONLINE": "ଅନଲାଇନ୍",
    "LISTENING": "ଶୁଣୁଛି",
    "LIVE": "ଲାଇଭ୍",
    "HIGH": "ଉଚ୍ଚ",
    "MEDIUM": "ମଧ୍ୟମ",
    "LOW": "କମ୍",
    "NEW": "ନୂଆ",
    "KNOWN": "ଜଣାଶୁଣା",
    "UNKNOWN": "ଅଜଣା",
    "NORMAL": "ସାଧାରଣ",
    "CHANGED": "ପରିବର୍ତ୍ତିତ",
    "CONNECTED": "ସଂଯୁକ୍ତ",
    "DETECTED": "ଚିହ୍ନଟ",
    "SUSPICIOUS": "ସନ୍ଦେହଜନକ",
    "PENDING": "ବକେୟା",
    "REVIEWED": "ସମୀକ୍ଷିତ",
    "ALLOWED": "ଅନୁମତିପ୍ରାପ୍ତ",
    "BLOCKED": "ବ୍ଲକ୍ ହୋଇଛି",
    "ALLOW": "ଅନୁମତି ଦିଅନ୍ତୁ",
    "BLOCK": "ବ୍ଲକ୍ କରନ୍ତୁ",
    "REVIEW": "ସମୀକ୍ଷା",
    "AMOUNT": "ରାଶି",
    "AMOUNT AT RISK": "ବିପଦରେ ଥିବା ରାଶି",
    "STATUS": "ସ୍ଥିତି",
    "DECISION": "ନିଷ୍ପତ୍ତି",
    "ACTIONS": "କାର୍ଯ୍ୟଗୁଡ଼ିକ",
    "LOCATION": "ସ୍ଥାନ",
    "LOCATIONS": "ସ୍ଥାନଗୁଡ଼ିକ",
    "DEVICE": "ଡିଭାଇସ୍",
    "DEVICES": "ଡିଭାଇସ୍",
    "BENEFICIARY": "ଲାଭାର୍ଥୀ",
    "BENEFICIARIES": "ଲାଭାର୍ଥୀ",
    "CONNECTIONS": "ସଂଯୋଗ",
    "ENTITIES": "ଏଣ୍ଟିଟି",
    "ENTITY": "ଏଣ୍ଟିଟି",
    "TRANSACTION": "ଲେନଦେନ",
    "TRANSACTIONS": "ଲେନଦେନ",
    "ALERTS": "ଆଲର୍ଟ",
    "ANALYTICS": "ଆନାଲିଟିକ୍ସ",
    "NETWORK": "ନେଟୱର୍କ",
    "GEOGRAPHY": "ଭୂଗୋଳ",
    "ADMIN": "ଆଡମିନ୍",
    "USERS": "ବ୍ୟବହାରକାରୀ",
    "USER": "ବ୍ୟବହାରକାରୀ",
    "ANALYST": "ବିଶ୍ଳେଷକ",
    "ANALYST FEEDBACK": "ବିଶ୍ଳେଷକ ପ୍ରତିକ୍ରିୟା",
    "ANALYST REVIEW": "ବିଶ୍ଳେଷକ ସମୀକ୍ଷା",
    "RISK DISTRIBUTION": "ବିପଦ ବଣ୍ଟନ",
    "RISK OVERVIEW": "ବିପଦ ଅବଲୋକନ",
    "NETWORK TELEMETRY": "ନେଟୱର୍କ ଟେଲିମେଟ୍ରି",
    "INTELLIGENCE COVERAGE": "ଇଣ୍ଟେଲିଜେନ୍ସ କଭରେଜ୍",
    "NETWORK EDGES": "ନେଟୱର୍କ ଏଜ୍",
    "SUSPICIOUS": "ସନ୍ଦେହଜନକ",
    "GEOGRAPHIC FRAUD INTELLIGENCE": "ଭୌଗୋଳିକ ଠକେଇ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "GEOGRAPHIC INTELLIGENCE": "ଭୌଗୋଳିକ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "LIVE GEOGRAPHIC MONITORING": "ଲାଇଭ୍ ଭୌଗୋଳିକ ମନିଟରିଂ",
    "SYNC INTELLIGENCE": "ଇଣ୍ଟେଲିଜେନ୍ସ ସିଙ୍କ୍ କରନ୍ତୁ",
    "SYNCING...": "ସିଙ୍କ୍ ହେଉଛି...",
    "INVESTIGATION WORKFLOW": "ତଦନ୍ତ କାର୍ଯ୍ୟପ୍ରବାହ",
    "LOCATION RISK INTELLIGENCE": "ସ୍ଥାନ ବିପଦ ଇଣ୍ଟେଲିଜେନ୍ସ",
    "Observed Locations": "ପର୍ଯ୍ୟବେକ୍ଷିତ ସ୍ଥାନ",
    "Locations Requiring Attention": "ଧ୍ୟାନ ଆବଶ୍ୟକ ସ୍ଥାନ",
    "Continue Investigation": "ତଦନ୍ତ ଜାରି ରଖନ୍ତୁ",
    "Open Fraud Network": "ଠକେଇ ନେଟୱର୍କ ଖୋଲନ୍ତୁ",
    "Open Fraud Alerts": "ଠକେଇ ଆଲର୍ଟ ଖୋଲନ୍ତୁ",
    "Open Transaction Analyzer": "ଲେନଦେନ ବିଶ୍ଳେଷକ ଖୋଲନ୍ତୁ",
    "Open Voice Detector": "ଭଏସ୍ ଡିଟେକ୍ଟର ଖୋଲନ୍ତୁ",
    "Search alerts...": "ଆଲର୍ଟ ଖୋଜନ୍ତୁ...",
    "Search device, beneficiary or identifier...": "ଡିଭାଇସ୍, ଲାଭାର୍ଥୀ କିମ୍ବା ପରିଚୟକର୍ତ୍ତା ଖୋଜନ୍ତୁ...",
    "Search location, ID or city...": "ସ୍ଥାନ, ID କିମ୍ବା ସହର ଖୋଜନ୍ତୁ...",
    "Search transaction, risk or decision...": "ଲେନଦେନ, ବିପଦ କିମ୍ବା ନିଷ୍ପତ୍ତି ଖୋଜନ୍ତୁ...",
    "Search ID, name or location...": "ID, ନାମ କିମ୍ବା ସ୍ଥାନ ଖୋଜନ୍ତୁ...",
    "Try changing your search or risk filter.": "ଆପଣଙ୍କ ସର୍ଚ୍ଚ କିମ୍ବା ବିପଦ ଫିଲ୍ଟର୍ ବଦଳାଇ ଚେଷ୍ଟା କରନ୍ତୁ।",
    "Try a different search term or clear the filters.": "ଅନ୍ୟ ସର୍ଚ୍ଚ ଶବ୍ଦ ଚେଷ୍ଟା କରନ୍ତୁ କିମ୍ବା ଫିଲ୍ଟର୍ ସଫା କରନ୍ତୁ।",
    "View only": "କେବଳ ଦେଖନ୍ତୁ",
    "Synchronizing...": "ସିଙ୍କ୍ରୋନାଇଜ୍ ହେଉଛି...",
    "Syncing Intelligence...": "ଇଣ୍ଟେଲିଜେନ୍ସ ସିଙ୍କ୍ ହେଉଛି...",
  },
};

// Smaller word-level fallback catches labels that are constructed from
// several JSX nodes or weren't present in the phrase table.
const WORDS = {
  hi: {
    Fraud: "फ्रॉड", Security: "सुरक्षा", Intelligence: "इंटेलिजेंस",
    Dashboard: "डैशबोर्ड", Transaction: "लेनदेन", Transactions: "लेनदेन",
    Alert: "अलर्ट", Alerts: "अलर्ट", Analytics: "एनालिटिक्स", Network: "नेटवर्क",
    Geography: "भूगोल", Device: "डिवाइस", Devices: "डिवाइस", Beneficiary: "लाभार्थी",
    Beneficiaries: "लाभार्थी", Location: "स्थान", Locations: "स्थान", User: "उपयोगकर्ता",
    Users: "उपयोगकर्ता", Risk: "जोखिम", Score: "स्कोर", Level: "स्तर", High: "उच्च",
    Medium: "मध्यम", Low: "कम", New: "नया", Known: "ज्ञात", Unknown: "अज्ञात",
    Suspicious: "संदिग्ध", Activity: "गतिविधि", Review: "समीक्षा", Reviewed: "समीक्षित",
    Pending: "लंबित", Confirmed: "पुष्ट", False: "गलत", Positive: "सकारात्मक",
    Blocked: "ब्लॉक", Allowed: "अनुमत", Allow: "अनुमति", Block: "ब्लॉक", Amount: "राशि",
    Total: "कुल", Average: "औसत", Current: "वर्तमान", History: "इतिहास", Recent: "हाल के",
    Signals: "संकेत", Signal: "संकेत", Detected: "पता चला", Detection: "पहचान", Explainable: "समझाने योग्य",
    Explain: "समझाएँ", AI: "AI", Engine: "इंजन", Analysis: "विश्लेषण", Analyze: "विश्लेषण करें",
    Analyzing: "विश्लेषण हो रहा है", Protection: "सुरक्षा", Protect: "सुरक्षित करें", Privacy: "गोपनीयता",
    Features: "विशेषताएँ", Security: "सुरक्षा", Operations: "संचालन", Center: "केंद्र", Command: "कमांड",
    Live: "लाइव", Ready: "तैयार", Online: "ऑनलाइन", Active: "सक्रिय", Loading: "लोड हो रहा है",
    Refresh: "रिफ्रेश", Search: "खोजें", Clear: "साफ़ करें", Close: "बंद करें", Open: "खोलें",
    View: "देखें", Back: "वापस", Continue: "जारी रखें", Investigate: "जांच करें", Action: "कार्रवाई",
    Actions: "कार्रवाइयाँ", Context: "संदर्भ", Security: "सुरक्षा", Operations: "संचालन",
    Type: "प्रकार", ID: "ID", Connections: "कनेक्शन", Entity: "एंटिटी", Entities: "एंटिटी",
    Login: "लॉगिन", Logout: "लॉगआउट", Register: "रजिस्टर", Password: "पासवर्ड", Email: "ईमेल",
    Name: "नाम", Full: "पूरा", Account: "खाता", Create: "बनाएँ", Enter: "दर्ज करें",
    Confirm: "पुष्टि करें", Voice: "वॉइस", Phishing: "फ़िशिंग", Scam: "स्कैम", Call: "कॉल",
    Conversation: "बातचीत", Transcript: "ट्रांसक्रिप्ट", Upload: "अपलोड करें", Start: "शुरू करें",
    Stop: "रोकें", Waiting: "प्रतीक्षा", Microphone: "माइक्रोफ़ोन", Automatic: "स्वचालित",
    Network: "नेटवर्क", Geographic: "भौगोलिक", Location: "स्थान", Connected: "जुड़ा हुआ",
    Relationship: "संबंध", Relationships: "संबंध", Known: "ज्ञात", Require: "आवश्यक", Attention: "ध्यान",
    Recommended: "अनुशंसित", Immediate: "तुरंत", Investigation: "जांच", System: "सिस्टम", All: "सभी",
    Risk: "जोखिम", Decision: "निर्णय", Recommended: "अनुशंसित", Pending: "लंबित", Read: "पढ़ा हुआ",
    Unread: "अपठित", Recent: "हाल का", Recently: "हाल ही में", Normal: "सामान्य", Changed: "बदला हुआ",
    Loading: "लोड हो रहा है", Error: "त्रुटि", Failed: "विफल", Unable: "असमर्थ", Please: "कृपया",
    Enter: "दर्ज करें", Password: "पासवर्ड", Confirm: "पुष्टि करें", Choose: "चुनें", Language: "भाषा",
    English: "अंग्रेज़ी", Hindi: "हिन्दी", Odia: "ओड़िया", Security: "सुरक्षा", FraudShield: "FraudShield",
  },
  or: {
    Fraud: "ଠକେଇ", Security: "ସୁରକ୍ଷା", Intelligence: "ଇଣ୍ଟେଲିଜେନ୍ସ", Dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    Transaction: "ଲେନଦେନ", Transactions: "ଲେନଦେନ", Alert: "ଆଲର୍ଟ", Alerts: "ଆଲର୍ଟ", Analytics: "ଆନାଲିଟିକ୍ସ",
    Network: "ନେଟୱର୍କ", Geography: "ଭୂଗୋଳ", Device: "ଡିଭାଇସ୍", Devices: "ଡିଭାଇସ୍", Beneficiary: "ଲାଭାର୍ଥୀ",
    Beneficiaries: "ଲାଭାର୍ଥୀ", Location: "ସ୍ଥାନ", Locations: "ସ୍ଥାନ", User: "ବ୍ୟବହାରକାରୀ", Users: "ବ୍ୟବହାରକାରୀ",
    Risk: "ବିପଦ", Score: "ସ୍କୋର୍", Level: "ସ୍ତର", High: "ଉଚ୍ଚ", Medium: "ମଧ୍ୟମ", Low: "କମ୍",
    New: "ନୂଆ", Known: "ଜଣାଶୁଣା", Unknown: "ଅଜଣା", Suspicious: "ସନ୍ଦେହଜନକ", Activity: "କାର୍ଯ୍ୟକଳାପ",
    Review: "ସମୀକ୍ଷା", Reviewed: "ସମୀକ୍ଷିତ", Pending: "ବକେୟା", Confirmed: "ନିଶ୍ଚିତ", False: "ଭୁଲ୍",
    Positive: "ପଜିଟିଭ୍", Blocked: "ବ୍ଲକ୍", Allowed: "ଅନୁମତିପ୍ରାପ୍ତ", Allow: "ଅନୁମତି", Block: "ବ୍ଲକ୍",
    Amount: "ରାଶି", Total: "ମୋଟ", Average: "ହାରାହାରି", Current: "ବର୍ତ୍ତମାନ", History: "ଇତିହାସ",
    Recent: "ସମ୍ପ୍ରତିର", Signals: "ସଙ୍କେତ", Signal: "ସଙ୍କେତ", Detected: "ଚିହ୍ନଟ", Detection: "ଚିହ୍ନଟ",
    Explainable: "ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ", Explain: "ବ୍ୟାଖ୍ୟା କରନ୍ତୁ", AI: "AI", Engine: "ଇଞ୍ଜିନ୍", Analysis: "ବିଶ୍ଳେଷଣ",
    Analyze: "ବିଶ୍ଳେଷଣ କରନ୍ତୁ", Protection: "ସୁରକ୍ଷା", Protect: "ସୁରକ୍ଷିତ କରନ୍ତୁ", Privacy: "ଗୋପନୀୟତା",
    Features: "ବୈଶିଷ୍ଟ୍ୟ", Operations: "ଅପରେସନ୍", Center: "କେନ୍ଦ୍ର", Command: "କମାଣ୍ଡ", Live: "ଲାଇଭ୍",
    Ready: "ପ୍ରସ୍ତୁତ", Online: "ଅନଲାଇନ୍", Active: "ସକ୍ରିୟ", Loading: "ଲୋଡ୍ ହେଉଛି", Refresh: "ରିଫ୍ରେଶ୍",
    Search: "ଖୋଜନ୍ତୁ", Clear: "ସଫା କରନ୍ତୁ", Close: "ବନ୍ଦ କରନ୍ତୁ", Open: "ଖୋଲନ୍ତୁ", View: "ଦେଖନ୍ତୁ",
    Back: "ଫେରନ୍ତୁ", Continue: "ଜାରି ରଖନ୍ତୁ", Investigate: "ତଦନ୍ତ କରନ୍ତୁ", Action: "କାର୍ଯ୍ୟ", Actions: "କାର୍ଯ୍ୟଗୁଡ଼ିକ",
    Context: "ପରିପ୍ରେକ୍ଷିତ", Type: "ପ୍ରକାର", ID: "ID", Connections: "ସଂଯୋଗ", Entity: "ଏଣ୍ଟିଟି", Entities: "ଏଣ୍ଟିଟି",
    Login: "ଲଗଇନ୍", Logout: "ଲଗଆଉଟ୍", Register: "ପଞ୍ଜୀକରଣ", Password: "ପାସୱାର୍ଡ", Email: "ଇମେଲ୍",
    Name: "ନାମ", Full: "ପୂର୍ଣ୍ଣ", Account: "ଆକାଉଣ୍ଟ", Create: "ତିଆରି କରନ୍ତୁ", Enter: "ଦିଅନ୍ତୁ",
    Confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ", Voice: "ଭଏସ୍", Phishing: "ଫିଶିଂ", Scam: "ସ୍କାମ୍", Call: "କଲ୍",
    Conversation: "କଥୋପକଥନ", Transcript: "ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ", Upload: "ଅପଲୋଡ୍ କରନ୍ତୁ", Start: "ଆରମ୍ଭ କରନ୍ତୁ",
    Stop: "ବନ୍ଦ କରନ୍ତୁ", Waiting: "ଅପେକ୍ଷା", Microphone: "ମାଇକ୍ରୋଫୋନ୍", Automatic: "ସ୍ୱୟଂଚାଳିତ",
    Geographic: "ଭୌଗୋଳିକ", Connected: "ସଂଯୁକ୍ତ", Relationship: "ସମ୍ପର୍କ", Relationships: "ସମ୍ପର୍କଗୁଡ଼ିକ",
    Require: "ଆବଶ୍ୟକ", Attention: "ଧ୍ୟାନ", Recommended: "ସୁପାରିଶ କରାଯାଇଥିବା", Immediate: "ତୁରନ୍ତ",
    Investigation: "ତଦନ୍ତ", System: "ସିଷ୍ଟମ୍", All: "ସମସ୍ତ", Decision: "ନିଷ୍ପତ୍ତି", Read: "ପଢ଼ା",
    Unread: "ଅପଢ଼ା", Recently: "ସମ୍ପ୍ରତି", Normal: "ସାଧାରଣ", Changed: "ପରିବର୍ତ୍ତିତ", Error: "ତ୍ରୁଟି",
    Failed: "ବିଫଳ", Unable: "ଅସମର୍ଥ", Please: "ଦୟାକରି", Choose: "ବାଛନ୍ତୁ", Language: "ଭାଷା",
    English: "ଇଂରାଜୀ", Hindi: "ହିନ୍ଦୀ", Odia: "ଓଡ଼ିଆ", FraudShield: "FraudShield",
  },
};

const ORIGINAL_TEXT = new WeakMap();
const ORIGINAL_ATTRIBUTES = new WeakMap();

function normalize(value) {
  return value.replace(/\s+/g, " ").trim();
}

function isDynamic(value) {
  const v = value.trim();
  if (!v) return true;
  if (/^https?:\/\//i.test(v)) return true;
  if (/^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$/.test(v)) return true;
  if (/^(₹|\$|€|£)?\s*[\d,]+(?:\.\d+)?(?:\s*\/\s*\d+)?$/.test(v)) return true;
  if (/^(DEV|BEN|TXN|UPI|ID)-?[A-Z0-9_-]+$/i.test(v)) return true;
  if (/^[A-Z0-9_-]{8,}$/.test(v) && /\d/.test(v)) return true;
  return false;
}

function preserveCase(source, translated) {
  if (source === source.toUpperCase() && /[A-Z]/.test(source)) {
    return translated.toUpperCase();
  }
  return translated;
}

function translate(value, language) {
  if (language === "en") return value;
  if (isDynamic(value)) return value;

  const phrases = PHRASES[language] || {};
  const normalized = normalize(value);
  if (phrases[normalized]) {
    const translated = phrases[normalized];
    return value.replace(normalized, translated);
  }

  let result = value;

  // Longest phrase first. This lets a sentence containing known labels
  // translate cleanly before falling back to individual words.
  const phraseKeys = Object.keys(phrases).sort((a, b) => b.length - a.length);
  for (const key of phraseKeys) {
    if (!key || key.length < 3) continue;
    result = result.replace(new RegExp(`(^|[^\\p{L}])${escapeRegExp(key)}(?=$|[^\\p{L}])`, "giu"), (m, prefix) => `${prefix}${phrases[key]}`);
  }

  const words = WORDS[language] || {};
  result = result.replace(/[A-Za-z][A-Za-z'-]*/g, (word) => {
    if (words[word]) return preserveCase(word, words[word]);
    return word;
  });

  return result;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function shouldSkipElement(element) {
  if (!element) return true;
  if (element.closest("[data-no-translate]")) return true;
  return ["SCRIPT", "STYLE", "NOSCRIPT", "CODE", "PRE"].includes(element.tagName);
}

function applyLanguage(language) {
  const root = document.body;
  if (!root) return;

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  let node;
  while ((node = walker.nextNode())) textNodes.push(node);

  for (const textNode of textNodes) {
    const parent = textNode.parentElement;
    if (shouldSkipElement(parent)) continue;
    if (!ORIGINAL_TEXT.has(textNode)) {
      ORIGINAL_TEXT.set(textNode, textNode.nodeValue || "");
    }
    const original = ORIGINAL_TEXT.get(textNode) || "";
    textNode.nodeValue = translate(original, language);
  }

  // Translate user-facing attributes such as placeholders and tooltips.
  const elements = root.querySelectorAll("input, textarea, button, [title], [aria-label]");
  for (const element of elements) {
    if (shouldSkipElement(element)) continue;

    for (const attr of ["placeholder", "title", "aria-label"]) {
      if (!element.hasAttribute(attr)) continue;
      const key = `${attr}:${element}`;
      let records = ORIGINAL_ATTRIBUTES.get(element);
      if (!records) {
        records = {};
        ORIGINAL_ATTRIBUTES.set(element, records);
      }
      if (!(attr in records)) records[attr] = element.getAttribute(attr) || "";
      element.setAttribute(attr, translate(records[attr], language));
    }
  }
}

export default function GlobalLanguageApplier() {
  const { language } = useLanguage();

  useEffect(() => {
    let timer;
    let observer;
    let applying = false;

    const run = () => {
      clearTimeout(timer);
      timer = setTimeout(() => {
        if (applying) return;
        applying = true;
        applyLanguage(language);
        applying = false;
      }, 0);
    };

    run();

    observer = new MutationObserver((mutations) => {
      // Route changes and async page sections create/remove DOM nodes.
      // Watch childList only so dynamic API values are never mistaken for
      // source-language strings and overwritten by the translator.
      if (mutations.some((m) => m.type === "childList" && (m.addedNodes.length || m.removedNodes.length))) {
        run();
      }
    });

    if (document.body) {
      observer.observe(document.body, {
        childList: true,
        subtree: true,
      });
    }

    return () => {
      clearTimeout(timer);
      observer?.disconnect();
    };
  }, [language]);

  return null;
}
